### ISSUE TITLE
Typo in Google::Ads::GoogleAds::GoogleAdsClient

### ISSUE THREAD

**Issue by scotttesler** [googleads/google-ads-ruby#10]
### What?

When attempting to run [this example](https://github.com/googleads/google-ads-ruby/blob/85eff72797e0c1a9a7d557366de6932c869affb1/examples/account_management/get_account_information.rb), the following error is raised:

```
NameError (uninitialized constant Google::Ads::GooglAads)
```

### Cause

In [`Google::Ads::GoogleAds::GoogleAdsClient`](https://github.com/googleads/google-ads-ruby/blob/a8553de62943608850bdcec58208e80d20d56e94/lib/google/ads/google_ads/google_ads_client.rb#L147), `Google::Ads::GoogleAds` is misspelled as `Google::Ads::GooglAads`.

---

I would open a PR to fix this, however I don't have appropriate permissions.

**Comment by mcloonan** [comment]
You should be able to make a pull request by forking the repo, according to this help article: https://help.github.com/articles/repository-permission-levels-for-an-organization/

If I don't see one from you in the next few days then I'll handle it. Thanks for pointing this out!

**Comment by scotttesler** [comment]
[Here's the PR](https://github.com/googleads/google-ads-ruby/pull/11).

**Comment by mcloonan** [comment]
Thanks!
