### ISSUE TITLE
ruby 1.8.7 support

### ISSUE THREAD

**Issue by hadan** [googleads/google-ads-ruby#111]
Hello,
May I know what's the latest version of google-ads-ruby that still support ruby 1.8.7?
Thank you.

**Comment by samphippen** [comment]
Hi @hadan!

Ruby 1.8.7 is not supported by any version of this library, our minimum supported version of Ruby is 2.3. Ruby 1.8.7 was released in 2008 and hasn't received security patches for several years at this point. If you're still running Ruby 1.8.7 we strongly suggest upgrading to a supported Ruby, before using this library.

Thanks :)
