### ISSUE TITLE
LROs don't work because headers aren't injectable

### ISSUE THREAD

**Issue by penelopezone** [googleads/google-ads-ruby#118]
P1 because we have released a library with a feature that users can't use.

**Comment by samphippen** [comment]
The context for this is that the `Google::Gax::OperationsClient` https://github.com/googleapis/gax-ruby/blob/1.x/lib/google/longrunning/operations_client.rb#L150 doesn't let us inject `headers`. We need to be able to pass `developer-token` and `login-customer-id` to be able to successfully complete the `reload` method (which is called by `wait_until_done!`, etc).

**Comment by samphippen** [comment]
Updated with a monkey patch in #119, will release a full fix one gax has upstreamed our patch.
