### ISSUE TITLE
Support default timeout flag in config file

### ISSUE THREAD

**Issue by mcloonan** [googleads/google-ads-ruby#124]
We should be able to support customizeable timeouts in the library config, with a sane default value

**Comment by mcloonan** [comment]
We may not need to do this anymore with the new backend, since you can specify options on a per-request basis now pretty easily.

**Comment by apneadiving** [comment]
Hi, could you please guide to where/how the timeout option can be set? Thanks!

**Comment by mcloonan** [comment]
You can do it a few ways.

This will update the timeout for all requests made with a given instance of a service going forward:

    service = client.service.google_ads
    service.configure do |config|
      config.timeout = time_in_seconds
    end

You can see the default values in the service client definition. For example: https://github.com/googleads/google-ads-ruby/blob/master/lib/google/ads/google_ads/v6/services/google_ads_service/client.rb#L62

You can also override for a specific call:

    client.service.google_ads.search(
      request: {
        ... request params like customer_id, query ...
      },
      options: {
        timeout: time_in_seconds
      }
    )

The options is a Gapic::CallOptions and supports all the same options shown above in the default service config. Note, if you want to use options, you must specify the request as shown above (i.e. explicitly using the request kwarg and providing a hash). The gapic layer expects all calls formatted this way, but we've built in a shortcut so if you don't want to specify any options, you can treat the request params as top-level kwargs.

**Comment by apneadiving** [comment]
Thanks! Crystal clear :)
Is it for both retrieving and mutating data?

**Comment by mcloonan** [comment]
Yeah, the same premise should apply to all API requests. If you find a case where it doesn't seem to work, please let me know :)
