### ISSUE TITLE
Hard coded values in add_campaign_draft code example

### ISSUE THREAD

**Issue by PierrickVoulet** [googleads/google-ads-ruby#132]
Hello,

I just spotted that there are two hard coded values that should not be in the add_campaign_draft code example:
https://github.com/googleads/google-ads-ruby/blob/2ef08fa7c7396f70391b11a6060efd021f5f823e/examples/campaign_management/add_campaign_draft.rb#L86

Thanks,

**Comment by mcloonan** [comment]
Thanks! Fixed.
