### ISSUE TITLE
GaxError Exception occurred in retry method that was not classified as transient, caused by 13:Internal error encountered. (Google::Gax::RetryError)

### ISSUE THREAD

**Issue by jairobluecaribu** [googleads/google-ads-ruby#14]
Hello,I try to get all keywords to many Accounts but the process launch this exception:

```
#<Thread:0x0000000002701258@reportsDaily.rb:454 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	11: from reportsDaily.rb:454:in `block (2 levels) in KeywordReportDaily'
	10: from reportsDaily.rb:476:in `threadReportkw'
	 9: from reportsDaily.rb:476:in `each'
	 8: from reportsDaily.rb:492:in `block in threadReportkw'
	 7: from reportsDaily.rb:492:in `count'
	 6: from /usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:160:in `each'
	 5: from /usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:173:in `each_page'
	 4: from /usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:173:in `loop'
	 3: from /usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:175:in `block in each_page'
	 2: from /usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:189:in `next_page'
	 1: from /usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:358:in `block in retryable'
/usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:369:in `rescue in block in retryable': GaxError Exception occurred in retry method that was not classified as transient, caused by 13:Internal error encountered. (Google::Gax::RetryError)
Traceback (most recent call last):
	11: from reportsDaily.rb:454:in `block (2 levels) in KeywordReportDaily'
	10: from reportsDaily.rb:476:in `threadReportkw'
	 9: from reportsDaily.rb:476:in `each'
	 8: from reportsDaily.rb:492:in `block in threadReportkw'
	 7: from reportsDaily.rb:492:in `count'
	 6: from /usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:160:in `each'
	 5: from /usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:173:in `each_page'
	 4: from /usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:173:in `loop'
	 3: from /usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:175:in `block in each_page'
	 2: from /usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:189:in `next_page'
	 1: from /usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:358:in `block in retryable'
/usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:369:in `rescue in block in retryable': GaxError Exception occurred in retry method that was not classified as transient, caused by 13:Internal error encountered. (Google::Gax::RetryError)
[ec2-user@ip-172-31-44-96 rbfiles]$ 
```

I get it only sometimes, 

could you help me? 
thanks

**Comment by mcloonan** [comment]
Can you provide a small code snippet that reproduces this? Short of that, can you rescue the exception and inspect it and print out any extra details that might help? Can you describe in more detail exactly what the difference is between requests that succeed and requests that fail?

**Comment by jairobluecaribu** [comment]
Hello,I have discovered that is happen when I try to run 20 threads o more to downloading reports. If you think that this is a API error (your side), I can to send more details. if you do not believe it, you can close this line, thank for your help, blesses

Details about Exception:
`data exception:

                 Message -> GaxError Exception occurred in retry method that was not classified as transient, caused by 13:Internal error encountered. 

                 inspect -> #<Google::Gax::RetryError: GaxError Exception occurred in retry method that was not classified as transient, caused by 13:Internal error encountered.>

                 backtrace -> /usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:369:in `rescue in block in retryable'
/usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:358:in `block in retryable'
/usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:189:in `next_page'
/usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:175:in `block in each_page'
/usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:173:in `loop'
/usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:173:in `each_page'
/usr/local/rvm/gems/ruby-2.5.1/gems/google-gax-1.4.0/lib/google/gax/api_callable.rb:160:in `each'
reportsDaily.rb:495:in `block in threadReportkw'
reportsDaily.rb:478:in `each'
reportsDaily.rb:478:in `threadReportkw'
reportsDaily.rb:456:in `block (2 levels) in KeywordReportDaily'
`

**Comment by jairobluecaribu** [comment]
mm the issue is not the Threads. this happen when a Query return a number bigger that Page_length given. SearchGoogleAdsResponse return "next_page_token" but anyway launch the exception

**Comment by mcloonan** [comment]
Can you give an example query and customer ID that causes this response? I want to see if it's specific to the Ruby library or a general issue with the API.

**Comment by jairobluecaribu** [comment]
Sure,
Account id: 403-769-2537

Query:

`@query_kw= <<~QUERY
            SELECT
                customer.id,
                customer.currency_code,
                campaign.id,
                ad_group.id,
                ad_group_criterion.criterion_id,
                ad_group_criterion.keyword.text,
                ad_group_criterion.negative,
                ad_group_criterion.keyword.match_type,
                ad_group_criterion.quality_info.quality_score,
                metrics.clicks,
                metrics.ctr,
                metrics.average_position,
                metrics.impressions,
                metrics.cost_micros,
                metrics.average_cpc,
                metrics.conversions_from_interactions_rate,
                metrics.conversions,
                metrics.cost_per_conversion,
                metrics.search_rank_lost_impression_share
            FROM keyword_view
            WHERE date DURING TODAY
            AND campaign.status='ENABLED'
            AND ad_group.status='ENABLED'
            AND ad_group_criterion.status='ENABLED'
        QUERY`


PAGE_SIZE = 1000

**Comment by mcloonan** [comment]
I was able to successfully fetch the next page both with raw CURL requests and with the Ruby client library. How are you trying to page through the results? I used the pattern shown in the get_keyword_stats.rb example: https://github.com/googleads/google-ads-ruby/blob/master/examples/reporting/get_keyword_stats.rb

**Comment by mcloonan** [comment]
I tested without "LIMIT 50" as well, fetching 1000 per page, and had no issues. What version of the gem are you using?

**Comment by mcloonan** [comment]
Sorry this has been left unlooked at for a long time. Are you still experiencing this issue with intermittent errors on requests that succeed other times?

**Comment by RodrigoMZ** [comment]
Hey
We are suffering the same error very often, with different services.
We figure out that if we make retry several times we get results, so looks like the problem is on the library.
Our last occurrence was few minutes ago :(

**Comment by vitorrd** [comment]
Hello.

The comment above was more than 18 months ago, and this is still happening. Can we get any response as V6 is issuing this error, and as you know, debugging is hard when the error doesn't tell you anything at all.

Thank you kindly.

**Comment by mcloonan** [comment]
I have seen this cryptic error message in the past, but it as always been something in my code, such as passing the customer ID as an integer instead of a string, or similar.

Can you provide some up-to-date code that reproduces this error on your side so I can see if I can figure out what's going wrong?

**Comment by vitorrd** [comment]
> I have seen this cryptic error message in the past, but it as always been something in my code, such as passing the customer ID as an integer instead of a string, or similar.
> 
> Can you provide some up-to-date code that reproduces this error on your side so I can see if I can figure out what's going wrong?

I'm currently away from my computer, but the smallest way I could reproduce was creating a campaign_budget with total_amount_micros and then calling google_ads.mutate. I found if total_amount_micros is present, the cryptic error is there.

I can provide code soon, but minimum reproducible can be done as per above.

Thanks.
