### ISSUE TITLE
inconsistencies between documentation and library behaviour

### ISSUE THREAD

**Issue by apneadiving** [googleads/google-ads-ruby#143]
I initially reported these [in the forum](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/adwords-api/m-xCUMeb-6Y/T-zShRnOBgAJ) but they told me to post here.

I would like to report some glitches I faced while implementing google ads code using https://github.com/googleads/google-ads-ruby

Basically it's a matter of documentation stating entities are editable while they are not (or maybe partially, yet would deserve clarification).

I put below the list of entities we did check alongside the error messages we got:

- Keywords: `'keyword.match_type' cannot be modified by 'UPDATE'` so we cant rely on mere update

- AdCustomizerFeedMapping: bug in the gem maybe, cannot update: `undefined method `update=' for #<Google::Ads::GoogleAds::V1::Services::FeedMappingOperation:0x00007f211f40b540`

- Location: `Field 'location.geo_target_constant' cannot be modified by 'UPDATE' operation – Field 'negative' cannot be modified by 'UPDATE' operation.`

- Proximity: `'proximity.geo_point.latitude_in_micro_degrees' cannot be modified by 'UPDATE' --Field 'proximity.radius' cannot be modified by 'UPDATE'` etc...

- ExpandedTextAd: `Field 'ad.expanded_text_ad.description' cannot be modified by 'UPDATE' operation., at operations[0].update.ad.expanded_text_ad.description", details: [<Google::Protobuf::Any: type_url: "type.googleapis.com/google.ads.googleads.v1.errors.GoogleAdsFailure", value: "\n\x9C\x01\n\x02\b\v\x12QField 'ad.expanded_text_ad.description' cannot be modified by 'UPDATE' operation.\"C\x12\x0E\n\noperations\x12\x00\x12\b\n\x06update\x12\x04\n\x02ad\x12\x12\n\x10expanded_text_ad\x12\r\n\vdescription\n\xA2\x01\n\x02\b\v\x12TField 'ad.expanded_text_ad.headline_part1' cannot be modified by 'UPDATE' operation.\"F\x12\x0E\n\noperations\x12\x00\x12\b\n\x06update\x12\x04\n\x02ad\x12\x12\n\x10expanded_text_ad\x12\x10\n\x0Eheadline_part1\n\xA2\x01\n\x02\b\v\x12TField 'ad.expanded_text_ad.headline_part2' cannot be modified by 'UPDATE' operation.\"F\x12\x0E\n\noperations\x12\x00\x12\b\n\x06update\x12\x04\n\x02ad\x12\x12\n\x10expanded_text_ad\x12\x10\n\x0Eheadline_part2\n\x90\x01\n\x02\b\v\x12KField 'ad.expanded_text_ad.path1' cannot be modified by 'UPDATE' operation.\"=\x12\x0E\n\noperations\x12\x00\x12\b\n\x06update\x12\x04\n\x02ad\x12\x12\n\x10expanded_text_ad\x12\a\n\x05path1\n\x90\x01\n\x02\b\v\x12KField 'ad.expanded_text_ad.path2' cannot be modified by 'UPDATE' operation.\"=\x12\x0E\n\noperations\x12\x00\x12\b\n\x06update\x12\x04\n\x02ad\x12\x12\n\x10expanded_text_ad\x12\a\n\x05path2\nu\n\x02\b\v\x12?Field 'ad.final_urls' cannot be modified by 'UPDATE' operation.\".\x12\x0E\n\noperations\x12\x00\x12\b\n\x06update\x12\x04\n\x02ad\x12\f\n\nfinal_urls">]`

- AdCustomizerFeed: `The customer is not eligible to mutate this resource.` Yet delete/create work fine

- CampaignAdSchedule: `Field 'ad_schedule.day_of_week' cannot be modified by 'UPDATE' operation., at operations[1].update.ad_schedule.day_of_week", details: [<Google::Protobuf::Any: type_url: "type.googleapis.com/google.ads.googleads.v1.errors.GoogleAdsFailure", value: "\n\x8B\x01\n\x02\b\v\x12IField 'ad_schedule.day_of_week' cannot be modified by 'UPDATE' operation.\":\x12\x10\n\noperations\x12\x02\b\x01\x12\b\n\x06update\x12\r\n\vad_schedule\x12\r\n\vday_of_week\n\x85\x01\n\x02\b\v\x12FField 'ad_schedule.end_hour' cannot be modified by 'UPDATE' operation.\"7\x12\x10\n\noperations\x12\x02\b\x01\x12\b\n\x06update\x12\r\n\vad_schedule\x12\n\n\bend_hour\n\x89\x01\n\x02\b\v\x12HField 'ad_schedule.end_minute' cannot be modified by 'UPDATE' operation.\"9\x12\x10\n\noperations\x12\x02\b\x01\x12\b\n\x06update\x12\r\n\vad_schedule\x12\f\n\nend_minute\n\x89\x01\n\x02\b\v\x12HField 'ad_schedule.start_hour' cannot be modified by 'UPDATE' operation.\"9\x12\x10\n\noperations\x12\x02\b\x01\x12\b\n\x06update\x12\r\n\vad_schedule\x12\f\n\nstart_hour\n\x8D\x01\n\x02\b\v\x12JField 'ad_schedule.start_minute' cannot be modified by 'UPDATE' operation.\"`

**Comment by mcloonan** [comment]
Most of these are in fact intended API behavior. Not all fields are mutable, and that's on the API side, not on the client library side. You'd get the same error message no matter what client library or other mechanism you used to try to initiate that update.

As for the AdCustomizerFeedMapping, can you share a short code snippet to show what you're trying to do so I can look into that error?

**Comment by apneadiving** [comment]
`AdCustomizerFeedMapping` must be an error from us. I was sure the doc said it could be updated but I cant find it anymore...

For the others, it is confusing to read entities are updatable but actually not really because some fields are not. So yes its a matter of documentation this is why I reported on the general forum first but they routed me there :)

**Comment by mcloonan** [comment]
Can you point me at a doc for a field that is actually immutable but where the doc says it's mutable? If I can identify a pattern then I'll work on finding someone to fix it.

**Comment by apneadiving** [comment]
For instance, we can see a [keyword](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.services#google.ads.googleads.v2.services.AdGroupCriterionOperation) can be updated, and there is no restriction on the fields in the [documentation](https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v2.common#google.ads.googleads.v2.common.KeywordInfo).
Whereas we face `'keyword.match_type' cannot be modified by 'UPDATE'` if we try to change the `match_type`.

Pretty much all examples are alike. Tell me if you need more :)

**Comment by mcloonan** [comment]
Thanks for the example. This isn't specifically related to this library, so I'm going to close out this issue, but I have filed an internal issue for us to investigate ways to improve the documentation around this. Thanks again for pointing it out!
