### ISSUE TITLE
CampaignDraftService is missing from ruby client library v1.1.1

### ISSUE THREAD

**Issue by pagipunit** [googleads/google-ads-ruby#153]
I wanted to create a campaign experiment and as the first step I need to create a draft campaign. The document says there is CampaignDraftService but the client is missing this service
 
@client.service(:CampaignDraft)
=> No service found with name CampaignDraft

**Comment by samphippen** [comment]
@pagipunit please try upgrading to version 2.4.1 of the library and see if that works for you. We are no longer supporting the 1.x series of this library (although V1 of the API is supported in 2.x of the library)

**Comment by pagipunit** [comment]
That seems to be working thanks.
