### ISSUE TITLE
Account hierarchy

### ISSUE THREAD

**Issue by v3rmin** [googleads/google-ads-ruby#16]
I try to fetch account hierarchy for a managed account using a single query.

```ruby
ga_service = client.service(:GoogleAds)
query = <<~QUERY
SELECT customer_client_link.client_customer, customer.descriptive_name
FROM customer_client_link
QUERY
response = ga_service.search('<MCC_ACCOUNT_ID>', query, page_size: 10)
```
The `descriptive_name` returned is the name of the MCC account not client.

How would you do it?

**Comment by v3rmin** [comment]
So I tried to fetch sub accounts without using google ads query language.

```ruby
client = Google::Ads::GoogleAds::GoogleAdsClient.new do |config|
  config.refresh_token = '<REFRESH_TOKEN>'
  config.client_id = '<CLIENT_ID>'
  config.client_secret = '<CLIENT_SECRET>'
  config.developer_token = '<DEV_TOKEN>'
  config.login_customer_id = 123456789 # My root customer Id
end

customer_srv = client.service(:Customer)
customer_srv.list_accessible_customers.resource_names
```

**Error:**
```
Google::Gax::RetryError (GaxError Exception occurred in retry method that was not classified as transient, caused by Header values must be of type string or array)
```
**Gemfile**
```
gem 'google-ads-googleads', '0.7.0'
```

Is there a working example how to fetch account hierarchy?

**Comment by mcloonan** [comment]
You don't need to specify a login_customer_id for this type of query, but if you do decide to specify it, it may need to be a string rather than a number.

As for product-level questions, like how to make specific queries, please ask on our [product forum](https://groups.google.com/forum/#!forum/adwords-api). Issues in this tracker should be library-specific.

**Comment by v3rmin** [comment]
If `login_customer_id` should be a String then why raise `Invalid login_customer_id. Must be an integer` at https://github.com/googleads/google-ads-ruby/blob/master/lib/google/ads/google_ads/google_ads_client.rb#L116-L119.
