### ISSUE TITLE
inserting 2 different campaign criterions for the same campaign

### ISSUE THREAD

**Issue by pagipunit** [googleads/google-ads-ruby#175]
I created a campaign and inserted a campaign criterion of type LOCATION = US for the it, it was performed successfully. Then I inserted a criterion of type LANGUAGE = English for it which also was performed successfully. But the original LOCATION criterion was deleted.

**Comment by samphippen** [comment]
@pagipunit can you show us the code you used to do this?

**Comment by pagipunit** [comment]
Reran the test today and it seems to be working now, closing this issue for now.
