### ISSUE TITLE
GoogleAdsError never raise in v2

### ISSUE THREAD

**Issue by javoeria** [googleads/google-ads-ruby#177]
After the v2 update, the exception `Google::Ads::GoogleAds::Errors::GoogleAdsError` never raise.

**Comment by samphippen** [comment]
@javoeria could you explain why *not* getting an error is causing issues for you?

**Comment by javoeria** [comment]
Basically to debug, I'm migrating the client to the new version and I get errors, but I can not know why it is failing, if it is due to a badly written parameter or something else.

**Comment by samphippen** [comment]
@javoeria could you post a sample error and backtrace?

**Comment by javoeria** [comment]
For example with this query _"SELECT customer.descriptive_namee FROM customer"_.
Before last update, the exception message was:
`"Unrecognized field in the query: 'customer.descriptive_namee'."`
Now, the exception message is:
`"GaxError Exception occurred in retry method that was not classified as transient, caused by 3:Request contains an invalid argument."`

Btw this is not new, the same problem occurred when the v1 was released and it was fixed a month later. Also you can try it with any example on the library, all have a rescue to GoogleAdsError.
