### ISSUE TITLE
Dismiss recommendation operation still failing

### ISSUE THREAD

**Issue by javoeria** [googleads/google-ads-ruby#18]
Hello, the last commit fixes one error but it raises another now, this happens because the file "recommendation_service_pb.rb" inside the v0/services folder is auto-generated incorrectly and needs changes to work properly.

That's why my pull request had changes inside v0 folder the first time.

`NameError: uninitialized constant Google::Ads::GoogleAds::V0::Services::DismissRecommendationOperation`

**Comment by mcloonan** [comment]
No, the auto-generated files aren't wrong; we need to adjust the util to their format, not the other way around.

I think the actual solution is to change 'DismissRecommendationOperation' to 'DismissRecommendationRequest::DismissRecommendationOperation' in the proto_lookup_util.rb on the line you added. Can you test if that fixes it and make another PR for that?

**Comment by javoeria** [comment]
It works, thanks.

**Comment by mcloonan** [comment]
Thanks so much for pointing this out and your help fixing it!
