### ISSUE TITLE
File permissions included in released gems are 640

### ISSUE THREAD

**Issue by yuroyoro** [googleads/google-ads-ruby#212]
When I install the gem and check the file permissions, it is 640 and cannot be read by other users.

```
$ wget https://rubygems.org/downloads/google-ads-googleads-5.1.0.gem .
$ tar xf google-ads-googleads-5.1.0.gem
$ tar xf data.tar.gz
$ ls -al lib/google/ads/google_ads.rb
-rw-r----- 1 ozaki ozaki 984  5月  8 16:06 lib/google/ads/google_ads.rb
```

`lib/google/ads/google_ads.rb` and other files has 0640 permissions.

Please fix to file permissions to 0644 to be able to read from other users.

**Comment by xflesym** [comment]
This is now fixed in the latest gem version:
https://rubygems.org/gems/google-ads-googleads/versions/12.0.0
