### ISSUE TITLE
Equivalent of VCR testing using this gem

### ISSUE THREAD

**Issue by qnm** [googleads/google-ads-ruby#244]
Hi!

I'm looking into using this gem in preference to the Adwords Api my company is currently using.

Currently we use rspec and VCR to record and replay live HTTP request and response as part of our automated tests.

As this gem uses GRPC, recording request/response is significantly harder.

How so you suggest I achieve a similar testing approach using GRPC?

**Comment by carpe171** [comment]
@qnm I'd be curious how you solved this problem.

**Comment by mcloonan** [comment]
It's certainly not as convenient as that, but you could route the API requests to your own local endpoint as part of the testing using the `api_endpoint` in the `Config`: https://github.com/googleads/google-ads-ruby/blob/master/lib/google/ads/google_ads/config.rb#L68

This setting isn't useful in production but for testing it may be useful. We also convert requests/responses to JSON in the logging interceptor, which isn't exactly the same as capturing the raw GRPC request/response, but might provide a good enough compromise.

**Comment by qnm** [comment]
@mcloonan @carpe171 I now have a working implementation using a branch of GCR: https://github.com/digivizer/gcr/tree/google-grpc-compatible

I'm happy to pull together some documentation if you think this will benefit others.

**Comment by spyderdfx** [comment]
@qnm Could you explain a bit more? I have a similar issue with vcr. Thanks in advance

**Comment by qnm** [comment]
@spyderdfx Hey! We're using the above branch to 'VCR' our GRPC requests. https://github.com/digivizer/gcr/tree/google-grpc-compatible

Here's how we use it in rspec with google analytics (don't have an ads one to hand, sorry), perhaps this will help:

```
before do
  GCR.cassette_dir = Rails.root.join('spec/fixtures/gcr')
  GCR.stub = GoogleAnalyticsV4::Service
               .new(token)
               .client
               .analytics_data_stub
               .grpc_stub
end
```

then in the test spec itself

```
it 'runs job' do
  VCR.use_cassette 'ga_token', :record => :once do
    GCR.with_cassette('ga') do
      job.perform_now(
        :token => token,
        :start_date => start_date,
        :end_date => end_date
      )
    end
  end
end
```

An OAUTH request happens each time you use the gem, so please use in tandem with VCR.

Let me know how you get on!

**Comment by qnm** [comment]
@carpe171 In case this is still relevant to you, I've added an example above!

**Comment by spyderdfx** [comment]
@qnm Thanks, that helps!
However, I got some weird behavior. With GCR enabled, I see two exactly the same outgoing requests instead of one. Ofc second request failed:

```
D, [2022-03-04T11:57:27.177239 #6] DEBUG -- : Outgoing request: Headers: {"developer-token":"REDACTED","x-goog-api-client":"gl-ruby/2.5.7 gccl/15.0.0 gax/0.6.0 gapic/15.0.0 grpc/1.43.1","x-goog-request-params":"customer_id=123"} Payload: {"customerId":"123","operations":[{"create":{"name":"2558 Region_1 AD_1 1","status":"PAUSED","advertisingChannelType":"SEARCH","networkSettings":{"targetGoogleSearch":true,"targetSearchNetwork":true,"targetContentNetwork":false},"campaignBudget":"customers/123/campaignBudgets/10507455975","manualCpc":{}}}]}
D, [2022-03-04T11:57:27.177528 #6] DEBUG -- : Incoming response: Payload: {"results":[{"resourceName":"customers/123/campaigns/16483454315"}]}

W, [2022-03-04T11:57:27.518687 #6]  WARN -- : CID: 123, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v9.services.CampaignService/MutateCampaigns, IsFault: yes, Request ID: lIg6Bnj7rEllpyOCXa7oMw
I, [2022-03-04T11:57:27.520497 #6]  INFO -- : Outgoing request: Headers: {"developer-token":"REDACTED","x-goog-api-client":"gl-ruby/2.5.7 gccl/15.0.0 gax/0.6.0 gapic/15.0.0 grpc/1.43.1","x-goog-request-params":"customer_id=123"} Payload: {"customerId":"123","operations":[{"create":{"name":"2558 Region_1 AD_1 1","status":"PAUSED","advertisingChannelType":"SEARCH","networkSettings":{"targetGoogleSearch":true,"targetSearchNetwork":true,"targetContentNetwork":false},"campaignBudget":"customers/123/campaignBudgets/10507455975","manualCpc":{}}}]}
I, [2022-03-04T11:57:27.520961 #6]  INFO -- : Incoming response (errors): 
  Google::Ads::GoogleAds::Errors::GoogleAdsError(Google::Ads::GoogleAds::Errors::GoogleAdsError): Trying to modify the name of an active or paused campaign
```

**Comment by irisyann** [comment]
> @spyderdfx Hey! We're using the above branch to 'VCR' our GRPC requests. https://github.com/digivizer/gcr/tree/google-grpc-compatible
> 
> Here's how we use it in rspec with google analytics (don't have an ads one to hand, sorry), perhaps this will help:
> 
> ```
> before do
>   GCR.cassette_dir = Rails.root.join('spec/fixtures/gcr')
>   GCR.stub = GoogleAnalyticsV4::Service
>                .new(token)
>                .client
>                .analytics_data_stub
>                .grpc_stub
> end
> ```
> 
> then in the test spec itself
> 
> ```
> it 'runs job' do
>   VCR.use_cassette 'ga_token', :record => :once do
>     GCR.with_cassette('ga') do
>       job.perform_now(
>         :token => token,
>         :start_date => start_date,
>         :end_date => end_date
>       )
>     end
>   end
> end
> ```
> 
> A regular HTTP token request happens each time you use the gem, so please use in tandem with VCR.
> 
> Let me know how you get on!

Hey there @qnm! Thanks for this. I'm still new to using GCR, could you explain a little more in detail about the below on how you define the stub?

`.analytics_data_stub`               
`.grpc_stub`

**Comment by tdutreui-solocal** [comment]
@irisyann 
Here is an example :
```
require "gcr"

GCR.cassette_dir = Rails.root.join("spec/gcr_cassettes")

adw_credentials = {
 login_customer_id: xxx,
 client_id: xxx,
 client_secret: xxx,
 developer_token: xxx
}
GCR.stub = GRPC::ClientStub.new("googleads.googleapis.com:443", GRPC::Core::ChannelCredentials.new(adw_credentials))
```

**Comment by dorasun** [comment]
Hi @eslamodeh, what are you looking for an update on? The above thread is resolved
