### ISSUE TITLE
login-customer-id issue

### ISSUE THREAD

**Issue by apneadiving** [googleads/google-ads-ruby#259]
Hi and thanks for the gem!

I have seen a regression over the past few weeks:
- I use google ads api to check data is fine on adwords account
- whereas the code didnt change, it started failing

I dont know where this is coming from though.

Here is how I try and fetch data:
```
I, [2020-11-26T11:01:22.695645 #82]  INFO -- : Outgoing request: 
Headers: {"developer-token":"REDACTED","login-customer-id":"890599XXXX","x-goog-api-client":"gl-ruby/2.6.6 gax/0.3.4 gapic/8.0.0 grpc/1.32.0","x-goog-request-params":"customer_id=820539XXXX"} 
Payload: {"customerId":"820539XXXX","query":"SELECT campaign_budget.id FROM campaign_budget WHERE campaign_budget.status != 'REMOVED'"}
I, [2020-11-26T11:01:22.696546 #82]  INFO -- : Incoming response (errors): 
Google::Ads::GoogleAds::Errors::GoogleAdsError(Google::Ads::GoogleAds::Errors::GoogleAdsError): 
User doesn't have permission to access customer. 
Note: If you're accessing a client customer, the manager's customer id must be set in the 'login-customer-id' header. 
See https://developers.google.com/google-ads/api/docs/concepts/call-structure#login-customer-id
```

I dont really know what to do here:
As you can see `login-customer-id` is indeed part of the headers. I double checked in the Adwords UI and `820539XXXX` is indeed a child of `890599XXXX`.

Could you please advise:
- is it gem related?
- or broader?

Thanks in advance!

**Comment by mcloonan** [comment]
This is almost certainly not related to the library. The library is passing along the header fine so there has to be something else going on. I suggest you contact our API support team here: https://groups.google.com/forum/#!forum/adwords-api
