### ISSUE TITLE
True/false command line arguments are awkward in examples

### ISSUE THREAD

**Issue by mcloonan** [googleads/google-ads-ruby#265]
See: https://github.com/googleads/google-ads-ruby/blob/master/examples/shopping_ads/add_shopping_product_ad.rb#L219

To leave it false, you have to not pass the command line that argument at all. To set it to true, you have to set the flag *and* a value, and the value doesn't matter. Even specifying "false" will result in the flag being set to true.

We should make this behave closer to boolean flags on other command line tools, where the act of setting the flag itself is enough to change it to true, with no value required.

**Comment by wfansh** [comment]
impacted examples:

add_shopping_product_ad.rb
add_shopping_product_listing_group_tree.rb
add_shopping_smart_ad.rb

I would suggest using sth. like "--create-default-listing-group true" or "--create-default-listing-group false"
