### ISSUE TITLE
Ad service undefined

### ISSUE THREAD

**Issue by javoeria** [googleads/google-ads-ruby#30]
Hello, i'm trying to update an ad and i'm having some problems.
I can update an ad_group_ad perfectly but i try to update the "final_urls" field of the ad inside the ad_group_ad and it gets an error:

`Field 'ad.final_urls' cannot be modified by 'UPDATE' operation.` 

Then, i try to use the client path of the ad but it's not defined in the "path_lookup_util.rb" file and it gets a NoMethod error:

`NoMethodError: undefined method 'ad' for #<Google::Ads::GoogleAds::PathLookupUtil>`

And finally, i try to define the method by myself in the gem but it gets another error:

`ArgumentError: No service found with name Ad`

So, it looks like the service of the Ad resource is not defined and i can't do any operations with them.
Any help? Thanks.

**Comment by mcloonan** [comment]
The AdService doesn't exist in the Google Ads API yet. See: https://developers.google.com/google-ads/api/reference/rpc/google.ads.googleads.v0.services

For now in the Google Ads API you'll have to do it the old way, by deleting the ad and creating a new one. I'll let the team know that this functionality is missing to make sure they're aware so we can be sure that it makes a future release.

**Comment by javoeria** [comment]
This is the way i'm doing it right now but there are some problems deleting and creating a new one too, for example i can't update an ad.image_ad because i need the "media_file" field to create it but that field is not selectable, so i can't get it to use it in the new ad.
Thanks for the response.

**Comment by mcloonan** [comment]
For product questions like this (i.e. things that would apply the same regardless of what language you're using, as opposed to issues that are specific to the Ruby library), you should ask in our [product forum](https://groups.google.com/forum/#!forum/adwords-api).

We have a team of support specialists who monitor the forum to help.
