### ISSUE TITLE
The error response comes back empty...

### ISSUE THREAD

**Issue by Mitsuru53** [googleads/google-ads-ruby#318]
Hi,

Sometimes when I throw a request to google api, I get an error and the error comes back empty!

My code like the following, ...

```
begin
  client.service.campaign_budget.mutate_campaign_budgets
rescue Google::Ads::GoogleAds::Errors::GoogleAdsError => e
  # error handling....
rescue GRPC::BadStatus => e
  # error handling....
rescue Google::Gax::RetryError => e
  # error handling....  
end
```

I have confirmed in the log that it goes into the rescue clause of GRPC::BadStatus, but the errors are empty as follows

```
ERROR -- : #&lt;Google::Ads::GoogleAds::Errors::GoogleAdsError: 47129443299440 &lt;Google::Ads::GoogleAds::V6::Errors::GoogleAdsFailure: errors: []
```

As a result of contacting Google, I was told that they can't tell without the request-id, but since the request-id is a property in the response, there is no way to tell if the response is empty...

If you have any insights, I'd appreciate your advice.
Thank you very much.

**Comment by mcloonan** [comment]
Request ID is actually sent in the trailing metadata of the response, not in the response body. So there is still a request ID, and you can get at it if you use some kind of external process to monitor network traffic.

Our library will start logging the request ID in the summary line as of the next release, so you could just wait for that and then rerun the query once that happens to generate a request ID for the support team to help you.

**Comment by Mitsuru53** [comment]
@mcloonan 
Thank you so much for your quick, detailed, explanations! It's very helpful and I appreciate your kindness!
I'm afraid this is a rudimentary question, but when an error is thrown, how do I get the trailing metadata of the response?
Also, when do you plan to release the next version?
I'm sorry for all the questions, but I'm looking forward to your reply!

**Comment by mcloonan** [comment]
The release has gone out last week, so you should be able to update now.

As for fetching the trailing metadata, there really isn't a great way to do it. You can see how we fetch it for logging here: https://github.com/googleads/google-ads-ruby/blob/master/lib/google/ads/google_ads/interceptors/logging_interceptor.rb#L87

You'll have to dig into the internals of the request a bit to get at the data yourself. Hopefully now that we're logging the request ID, there won't be any reason for you to do that.
