### ISSUE TITLE
Issue using latest 12.0.0 gem

### ISSUE THREAD

**Issue by apneadiving** [googleads/google-ads-ruby#325]
Hi,

I tried to update the gem to the latest version but face a weird issue:
```
client 
=> #<Google::Ads::GoogleAds::GoogleAdsClient:0x00007fa1a6c9c940 ...

client.service.google_ads
Traceback (most recent call last):
        1: from (irb):9
LoadError (cannot load such file -- /Users/xfx/github/release-sanity-check/lib/google/ads/google_ads/v8/services/google_ads_service)
```

I checked examples (https://developers.google.com/google-ads/api/docs/samples/get-keywords) and it seems to still be the valid syntax.

Worked fine with all previous versions, gem update is the only change.

Thanks in advance!

**Comment by xflesym** [comment]
Hi Benjamin, I'll take a look at the issue. Would you let me know the step to reproduce this? e.g. what code example did you run

**Comment by apneadiving** [comment]
Hi @xflesym I just built a client, then tried `client.service.google_ads`. Not much really

**Comment by xflesym** [comment]
I can reproduce the same issue on my side as well. Will investigate and fix ASAP.

**Comment by xflesym** [comment]
I've pushed a new gem version 12.0.1. Could you gem update again and see if the issue is fixed?

**Comment by apneadiving** [comment]
so yeah this one is solved but there is something else:

```
# using 12.0.1
client.resource.target_spend
=> <Google::Ads::GoogleAds::V8::Resources::AccessibleBiddingStrategy::TargetSpend: >

# using 11.0.0
client.resource.target_spend
<Google::Ads::GoogleAds::V7::Common::TargetSpend: >
```

which then leads to crashes as I cannot assign a `Google::Ads::GoogleAds::V8::Resources::AccessibleBiddingStrategy::TargetSpend` to a bid strategy

**Comment by xflesym** [comment]
This is because now we have two TargetSpend types under AccessibleBiddingStrategy and Common, which leads to a naming conflict using the client.resource.type syntax.

The workaround is to specify the full path to the type you need, e.g.

```
campaign.target_cpa = Google::Ads::GoogleAds::V8::Common::TargetCpa.new
campaign.target_cpa.target_cpa_micros = 5_000_000
```

We have issue #316 filed to address the name conflict issue. Please use the above workaround in the meanwhile.

**Comment by apneadiving** [comment]
ok thanks!
