### ISSUE TITLE
Missing path declaration?

### ISSUE THREAD

**Issue by apneadiving** [googleads/google-ads-ruby#327]
Hi,

For now, in the app I am working on, we retrieve all paths using:
```
lookup_util = ::Google::Ads::GoogleAds::LookupUtil.new
paths = lookup_util.path(:V8)
paths.campaign(customer: "111", campaign: "222")
=> "customers/111/campaigns/222"
paths.asset(customer: "111", asset: "222")
=> "customers/111/assets/222"
```
And it works fine.
Yet there is a glitch with `campaign_asset`:
```
paths.campaign_asset
Traceback (most recent call last):
        1: from (irb):35
NoMethodError (undefined method `campaign_asset' for #<Google::Ads::GoogleAds::Utils::V8::PathLookupUtil:0x00007fc92cef24a8>)
```

I am aware of `client.service.campaign_asset.campaign_asset_path` but is there a reason `campaign_asset` is not consistent with the other resources?

Thanks!

**Comment by apneadiving** [comment]
mmm seems to be missing in https://github.com/googleads/google-ads-ruby/blob/master/lib/google/ads/google_ads/utils/path_lookup_config.rb#L34

**Comment by mcloonan** [comment]
This was probably a mistake as that utility is hand-written (unfortunately). We're looking at making a way to automatically generate it in the future so this kind of thing shouldn't happen.

**Comment by xflesym** [comment]
gem 12.0.2 has been published. issue should be fixed now.
