### ISSUE TITLE
uninitialized constant Google::Ads::GoogleAds::V8

### ISSUE THREAD

**Issue by goldylucks** [googleads/google-ads-ruby#335]
Following [this doc](https://developers.google.com/google-ads/api/docs/samples/add-app-campaign), trying to access this throw an error
![image](https://user-images.githubusercontent.com/6963212/126067669-2cc37306-a962-407c-8d0a-0178d19a32e0.png)

I looked into the source code and it seems like the module is defined. Maybe it's not loaded?

```
   $ bundle show | grep google
  * google-ads-googleads (10.0.0)
  * google-protobuf (3.17.3)
  * googleapis-common-protos (1.3.11)
  * googleapis-common-protos-types (1.1.0)
  * googleauth (0.16.2)

```

**Comment by abraham** [comment]
Support for version 8 of the Google Ads API was added to version 12 of the gem. Please try updating to the latest version of the gem and that should resolve the issue.
