### ISSUE TITLE
uninitialized constant Google::Ads::GoogleAds::V6::Common::TargetCpa

### ISSUE THREAD

**Issue by goldylucks** [googleads/google-ads-ruby#336]
According to the [docs](https://developers.google.com/google-ads/api/reference/rpc/v6/TargetCpa), This should be available.

We can't upgrade to the latest gem due to dependencies issues, so we have to use v6 for now. how do I get `TargetCpa`? I need it to create an app campaign

btw, I can't seem to close #335 , please close it

**Comment by mcloonan** [comment]
This is the same as #325, which will be fixed in the next library release. I apologize for the inconvenience. That issue does mention a workaround in the meanwhile.

**Comment by goldylucks** [comment]
@mcloonan thanks for the quick repsonse
I don't see how the workaround is relevant for my issue. I can't access `TargetCpa` at all, so how do I assign these?

```
c.target_cpa = Google::Ads::GoogleAds::V8::Common::TargetCpa.new
c.target_cpa.target_cpa_micros = 10000000
```

**Comment by mcloonan** [comment]
Oh, if you're using an old gem then it should be as simple as `client.resource.target_cpa` (assuming that `client` is an instance of `GoogleAdsClient`). If you run that line, what happens?

**Comment by goldylucks** [comment]
This works!
