### ISSUE TITLE
API v8 - duplicate method definition in resources factory - breaking change

### ISSUE THREAD

**Issue by vijuSR** [googleads/google-ads-ruby#337]
The class method `metrics` in module `Google::Ads::GoogleAds::Factories::V8::Resources` has a duplicate definition. In gem version 13.0.0, both the definitions of this method can be found starting at lines 6344 & 6851. This is certainly a breaking change because the later definition changes the behavior of the metrics resource factory method. I could not find any reference or doc quoting this change and since the [factories methods for all the resources are automatically generated](https://developers.google.com/google-ads/api/docs/client-libs/ruby/factories). - this looks like a bug. Here are the 2 versions of the method:
1. this maintains the behavior wrt all the other api version resources factory
```ruby
module Google
  module Ads
    module GoogleAds
      module Factories
        module V8
          module Resources
            ...
            # at line 6344
            def self.metrics
              require "google/ads/google_ads/v8/common/metrics_pb"
              res = Google::Ads::GoogleAds::V8::Common::Metrics.new
              yield res if block_given?
              res
            end
            ...
         end  
      end
  end
end
```
2. unexpected
```ruby
module Google
  module Ads
    module GoogleAds
      module Factories
        module V8
          module Resources
            ...
            # at line 6851
            def self.metrics
              require "google/ads/google_ads/v8/services/smart_campaign_suggest_service_pb"
              res = Google::Ads::GoogleAds::V8::Services::SuggestSmartCampaignBudgetOptionsResponse::Metrics.new
              yield res if block_given?
              res
            end
            ...
         end  
      end
  end
end
```

**Comment by mcloonan** [comment]
This is the same as #316 and will be fixed in the next release. I just double-checked that the fix will also apply to this field. There's a workaround in the meanwhile in that issue.

Thanks for reporting!

**Comment by mariuszmikolajczak** [comment]
> There's a workaround in the meanwhile in that issue.

@mcloonan Can you tell me, where can I find this workaround. I'm struggling with `self.total_spend` currently which is duplicated in `v13.0.0` too.

**Comment by mcloonan** [comment]
Just use the full path to the class, for example: `Google::Ads::GoogleAds::V8::TargetSpend.new`
