### ISSUE TITLE
Injectable config.logger

### ISSUE THREAD

**Issue by jbodah** [googleads/google-ads-ruby#34]
Would it be possible to have an injectable `config.logger` (rather than just the stream/level)? We try to reuse `Rails.logger` or one of our custom logger instances whenever possible

**Comment by mcloonan** [comment]
You can pass your own logger via `client.logger = logger`. See: https://github.com/googleads/google-ads-ruby/blob/master/lib/google/ads/google_ads/google_ads_client.rb#L194

Does this work for you or would you prefer to also have that option directly on the config?

**Comment by jbodah** [comment]
This works and is how I've fixed it for now. If possible I'd prefer to keep STDERR clean and avoid the default logger creation attempt altogether though

**Comment by samphippen** [comment]
@jbodah please leave feedback on #57!
