### ISSUE TITLE
GRPC::InvalidArgument (3:Request contains an invalid argument.)

### ISSUE THREAD

**Issue by inmar-mohan** [googleads/google-ads-ruby#340]
Hi Team,

We have been using this gem to read `ad_campaigns`, `ad_groups`, and `ads` from the google ads for one year. All of a sudden we are getting an`GRPC::InvalidArgument (3:Request contains an invalid argument.)` error while performing any operation.

Here is what my code looks like:
`

    def client
      @client = Google::Ads::GoogleAds::GoogleAdsClient.new do |config|
        config.client_id = ENV['CLIENT_ID']
        config.client_secret = ENV['CLIENT_SECRET']
        config.refresh_token = ENV['REFRESH_TOKEN']
        config.developer_token = ENV['DEVELOPER_TOKEN']
        config.logger = Logger.new($stdout)
      end
    end

    def ad_campaign_query
      <<~SQL
        SELECT
          campaign.id,
          campaign.name,
          campaign.status
        FROM campaign
        ORDER BY campaign.id
      SQL
    end

    irb(main):054:0> response = client.service.google_ads.search_stream(ENV['CUSTOMER_ID'], ad_campaign_query)
    I, [2021-07-30T18:44:17.577008 #56]  INFO -- : CID: 3862983423, Host: googleads.googleapis.com:443, Method: 
    /google.ads.googleads.v4.services.GoogleAdsService/SearchStream, IsFault: no
    => #<Enumerator: #<Enumerator::Generator:0x000055f15417e5a8>:each>
    irb(main):055:0>
    irb(main):056:0> response.each do |batch|
    irb(main):057:1*       batch.results.each do |ad_campaign|
    irb(main):058:2*         ad_campaign
    irb(main):059:2>      end
    irb(main):060:1> end
    Traceback (most recent call last):
            3: from (irb):56
            2: from (irb):56:in `each'
            1: from (irb):56:in `each'
    GRPC::InvalidArgument (3:Request contains an invalid argument.)
    irb(main):061:0>
`

I have checked all my OAuth credentials, CUSTOMER_ID, and DEVELOPER_TOKEN and everything is perfect. I even tried with new REFRESH_TOKEN, but no luck. We have been facing this issue for a week and we are not able to figure out the issue. 

Could anyone please look into the issue? Please let me know if you need additional information. Any help or suggestions would be much appreciated.

Thanks

**Comment by mcloonan** [comment]
It looks like you're still using v4 of the API, which has been someset some time ago. Please upgrade to a new version of the gem and a new version of the API (v8 is the latest) and try again.

**Comment by inmar-mohan** [comment]
Upgrading to a newer version fixed the issue. Thanks, @mcloonan!
