### ISSUE TITLE
Failure on creating account budget proposal update operation 

### ISSUE THREAD

**Issue by pyhsieh-cyberbiz** [googleads/google-ads-ruby#341]
Hi Team,

I'm using ver. `13.0.0` now and following the instructions here to update existing account budget:
https://developers.google.com/google-ads/api/docs/billing/account-budgets#update

From the snippet, the full script should look like this:
```
proposal = client.resource.account_budget_proposal
proposal.proposal_type = :UPDATE

mask = client.field_mask.with proposal do
  proposal.account_budget = 'customers/XXXXXXXXXX/accountBudgets/XXXXXXXXXX'
  proposal.proposed_spending_limit_micros = 1_000_000_000
end

operation = client.operation.create_resource.account_budget_proposal do |op|
  op.create = proposal
  op.update_mask = mask
end

response = client.service.account_budget_proposal.mutate_account_budget_proposal(
  customer_id: 'XXXXXXXXXX',
  operation: operation,
)
```

And error happened on creating the operation:
```
NoMethodError: undefined method `create=' for #<Google::Ads::GoogleAds::V8::Resources::AccountBudgetProposal:0x000055cbc2b9a350>
```

The same for `update_mask` when swapping settings order:
```
operation = client.operation.create_resource.account_budget_proposal do |op|
  op.update_mask = mask
  op.create = proposal
end
```

```
NoMethodError: undefined method `update_mask=' for #<Google::Ads::GoogleAds::V8::Resources::AccountBudgetProposal:0x000055cbc2c3b368>
```

**Comment by mcloonan** [comment]
If you do `client.operation.create_resource.[entity_type]`, then the object passed into the block is a *resource* of that type, not an operation. If you want to act on the operation directly, you should be able to do `client.operation.[entity_type]` directly which will then pass the operation to the block instead.

Clearly the code example on that page is completely wrong. I'll look into getting that fixed as well.

**Comment by pyhsieh-cyberbiz** [comment]
Tried again and it works now! 😃 So it's actually doc typo (also the snippet's missing `end` in code blocks).
