### ISSUE TITLE
Possibility to obtain access token through Ads client

### ISSUE THREAD

**Issue by pyhsieh-cyberbiz** [googleads/google-ads-ruby#344]
Hi Team,

  I'm planning to automate process of downloading invoice PDF files through URL pulled from invoice service, which requires access token included in HTTP request.

  From the documentation below, it seems that all service clients maintain (refresh) access tokens internally:
https://developers.google.com/identity/protocols/oauth2/web-server#offline

  Is it possible to access/obtain access token from Ads client instance? If not, what's the recommended way to obtain access token when I already have refresh token (in Ruby)?

**Comment by mcloonan** [comment]
You supply the refresh token in the config file and the library handles access tokens automatically.

See here for complete information about the config file: https://developers.google.com/google-ads/api/docs/client-libs/ruby/configuration
