### ISSUE TITLE
"grpc_message":"Request contains an invalid argument.","grpc_status":3

### ISSUE THREAD

**Issue by adambedford** [googleads/google-ads-ruby#347]
Hi there,

I'm running into an issue when trying to execute a query for ad campaigns:

```
/Users/adam/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/google-ads-googleads-14.0.0/lib/google/ads/google_ads/interceptors/error_interceptor.rb:76:in `rescue in block in server_streamer': Google::Ads::GoogleAds::Errors::GoogleAdsError (Google::Ads::GoogleAds::Errors::GoogleAdsError)
/Users/adam/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/grpc-1.38.0-universal-darwin/src/ruby/lib/grpc/generic/active_call.rb:29:in `check_status': 3:Request contains an invalid argument.. debug_error_string:{"created":"@1630352327.914283000","description":"Error received from peer ipv6:[2607:f8b0:4007:803::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Request contains an invalid argument.","grpc_status":3} (GRPC::InvalidArgument)
```

The code we're trying to run is:

```ruby
client = ...

responses = client.service.google_ads.search_stream(
  customer_id: customer_id,
  query: 'SELECT campaign.id, campaign.name FROM campaign ORDER BY campaign.id',
)

responses.each do |response|
  response.results.each do |row|
    puts "Campaign with ID #{row.campaign.id} and name '#{row.campaign.name}' was found."
  end
end
```

Using v14 of this library, which I'm pretty sure is current and expected to work. Any insight into what's going wrong would be very helpful.

**Comment by mcloonan** [comment]
As a first guess, what is the `customer_id` you're sending. It must be in the form of a string, even though it is numeric, or else the request will fail. If that's not the problem I'll take a closer look and see if I can reproduce the issue.

**Comment by adambedford** [comment]
Thanks for the help and quick reply. I was sending a string but with the resource name: `"customers/8334064631"`. I just switched to the string `"8334064631"` but I'm getting the same error.

Client initialization looks like:
```ruby
class GoogleAdsInterface
  def self.client(service)
    Google::Ads::GoogleAds::GoogleAdsClient.new do |config|
      config.client_id = ENV["GOOGLE_CLIENT_ID"]
      config.client_secret = ENV["GOOGLE_CLIENT_SECRET"]
      config.refresh_token = service.refresh_token
      config.developer_token = ENV["GOOGLE_DEVELOPER_TOKEN"]
    end
  end
end

```

**Comment by adambedford** [comment]
Actually, apologies... the error message has now changed to `The caller does not have permission`. I've authenticated via Oauth2 and fetched the customer ID using the following call:

`accessible_customers = client.service.customer.list_accessible_customers().resource_names`

Which produces:

`["customers/8334064631"]`

**Comment by mcloonan** [comment]
Can you include the full API response that includes that error message?

**Comment by adambedford** [comment]
Here it is:

```
/Users/adam/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/google-ads-googleads-14.0.0/lib/google/ads/google_ads/interceptors/error_interceptor.rb:76:in `rescue in block in server_streamer': Google::Ads::GoogleAds::Errors::GoogleAdsError (Google::Ads::GoogleAds::Errors::GoogleAdsError)
/Users/adam/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/grpc-1.38.0-universal-darwin/src/ruby/lib/grpc/generic/active_call.rb:29:in `check_status': 7:The caller does not have permission. debug_error_string:{"created":"@1630354111.241563000","description":"Error received from peer ipv6:[2607:f8b0:4007:811::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"The caller does not have permission","grpc_status":7} (GRPC::PermissionDenied)
```

**Comment by mcloonan** [comment]
It looks like there could be a few possible causes for this.

1. You haven't accepted the terms and conditions, and you're making the call on a production account. Since you were able to fetch customers, though, I don't think this is the cause.
2. The account you're authenticating as does have access to that account, but the API side isn't realizing that. You can try specifying the `login_customer_id` in the config *before creating the service*. For example, add this line to your config code above:

        config.login_customer_id = "xxxxxxxxx"

**Comment by mcloonan** [comment]
In any case, I don't think that this issue is specific to the ruby library, so in the case that these don't help solve the issue, you should try reaching out to our dedicated API support team on the forum: https://groups.google.com/forum/#!forum/adwords-api

**Comment by adambedford** [comment]
@mcloonan Thanks for your help digging into this. I see now I only have Test Account access so I imagine that restricts fetching campaigns for a production Ads account? I've submitted a request for Basic Access so hopefully that'll clear up the issue :)

Thanks again.

**Comment by skarmakar** [comment]
@adambedford could you be able to figure out the issue? I am trying with the same credentials which work using the [google-adwords-api](https://github.com/googleads/google-api-ads-ruby) gem and still getting the same, even while executing

```ruby
accessible_customers = client.service.customer.list_accessible_customers().resource_names
```

Gem Version: 15.0.0 
Error
```
Google::Ads::GoogleAds::Errors::GoogleAdsError: Google::Ads::GoogleAds::Errors::GoogleAdsError
from /home/santanu/.rvm/gems/ruby-2.7.4@skrails6/gems/google-ads-googleads-15.0.0/lib/google/ads/google_ads/interceptors/error_interceptor.rb:67:in `rescue in request_response'
Caused by GRPC::PermissionDenied: 7:The caller does not have permission. debug_error_string:{"created":"@1639225636.086183553","description":"Error received from peer ipv4:172.217.163.170:443","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"The caller does not have permission","grpc_status":7}
from /home/santanu/.rvm/gems/ruby-2.7.4@skrails6/gems/grpc-1.42.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:29:in `check_status'
```

Thanks in advance!

**Comment by skarmakar** [comment]
@mcloonan https://github.com/googleads/google-ads-ruby/issues/347#issuecomment-991627815 may I get any help? totally stuck and not sure what's doing wrong!

**Comment by Luigi123** [comment]
I was having the same problem but managed to fix this error by simply updating the gem to version 18.0.0 (I was using 12.0.0).
Here's the error message I was getting:

```
/usr/local/bundle/gems/grpc-1.38.0/src/ruby/lib/grpc/generic/active_call.rb:29:in `check_status': 3:Request contains an invalid argument.. debug_error_string:{"created":"@1656561577.007575759","description":"Error received from peer ipv4:142.250.207.42:443","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Request contains an invalid argument.","grpc_status":3} (GRPC::InvalidArgument)

```

One thing that helped me identify my problem was enabling logging in the config like this:

```ruby
@client = Google::Ads::GoogleAds::GoogleAdsClient.new do |config|
  config.client_id = ENV["GOOGLE_CLIENT_ID"]
  config.client_secret = ENV["GOOGLE_CLIENT_SECRET"]
  config.refresh_token = "my refresh token"
  config.developer_token = ENV["GOOGLE_DEVELOPER_TOKEN"]
  config.log_level = "DEBUG"
  config.logger = Logger.new(STDOUT)
end
```

Enabling the logger and trying to download a report (the thing that was failing before) gave me this message:

```
I, [2022-06-30T03:59:37.027816 #8]  INFO -- : Incoming response (errors): 
  Google::Ads::GoogleAds::Errors::GoogleAdsError(Google::Ads::GoogleAds::Errors::GoogleAdsError):  Version v8 is deprecated. Requests to this version will be blocked.
```

I was using the version 12 of the gem (not v8), but still, I tried updating it to 18, which was released just a few days ago, and it solved the problem for me.

I see from the logs in this issue that people are using newer versions of the gem, but still, if anything enabling logging may lead you somewhere.

I hope this is any help. Cheers.
