### ISSUE TITLE
No .gem file published with release 14.0.0 

### ISSUE THREAD

**Issue by j-ochs** [googleads/google-ads-ruby#355]
We recently tried to install the current latest version of this gem (`14.0.0`) in our project.
It appears that this release is incomplete, as our app's deployment was unable to vendor the gem correctly - resulting in the following error when attempting to load the gem:
```
LoadError: cannot load such file -- /app/vendor/bundle/ruby/2.7.0/gems/google-ads-googleads-14.0.0/lib/google/ads/google_ads.rb
```

Peculiarly, you will see that the `.gem` file is not included in release [`14.0.0`](https://github.com/googleads/google-ads-ruby/releases/tag/google-ads-googleads%2Fv14.0.0), whereas it is included in previous releases (eg: [`13.0.0`](https://github.com/googleads/google-ads-ruby/releases/tag/google-ads-googleads%2Fv13.0.0)).

Rolling back the gem to versions prior to `14.0.0` has fixed this issue for us - so the issue does seem to be isolated to just this version.

**Comment by dimasusername** [comment]
I confirm, this is also broken in Docker.

`cannot load such file -- google/ads/google_ads`

Version 13 works.

**Comment by abraham** [comment]
The v14.0.0 release has been updated to include the gem.

RubyGems and bundler is the [recommend](https://github.com/googleads/google-ads-ruby#installation) way to install the gem.

**Comment by saurgoel** [comment]
Faceing the same issue with v15.0.0 (https://rubygems.org/gems/google-ads-googleads)
Any fixes for this?

`require "google/ads/google_ads"
Traceback (most recent call last):
        2: from (irb):1
        1: from (irb):2:in `rescue in irb_binding'
LoadError (cannot load such file -- google/ads/google_ads)`

**Comment by mcloonan** [comment]
The gem is attached to the [GitHub release](https://github.com/googleads/google-ads-ruby/releases/tag/google-ads-googleads%2Fv15.0.0) and is uploaded to [RubyGems](https://rubygems.org/gems/google-ads-googleads/versions/15.0.0) so it must be some issue with how you're installing it on your side.

We recommend using bundler, which would pull automatically from RubyGems once you get it set up.

**Comment by saurgoel** [comment]
@mcloonan 
On further digging figured out, it's a permission issue. The main file doesn't have the required executable permission, and hence there is an error when it's being required. I am using bundler for installing the gem, but seems like it's not setting the right permissions.

```
ls -la vendor/bundle/ruby/2.7.0/gems/google-ads-googleads-15.0.0/lib/google/ads/google_ads/google_ads_client.rb 
-rw-r----- 1 root root 9665 Dec 29 14:40 vendor/bundle/ruby/2.7.0/gems/google-ads-googleads-15.0.0/lib/google/ads/google_ads/google_ads_client.rb
```

Manually setting these permissions fixes the issue, but this isn't the ideal way.
The same issue has been reported with another gem - https://github.com/googleads/google-api-ads-ruby/issues/89

**Comment by saurgoel** [comment]
> @mcloonan On further digging figured out, it's a permission issue. The main file doesn't have the required executable permission, and hence there is an error when it's being required. I am using bundler for installing the gem, but seems like it's not setting the right permissions.
> 
> ```
> ls -la vendor/bundle/ruby/2.7.0/gems/google-ads-googleads-15.0.0/lib/google/ads/google_ads/google_ads_client.rb 
> -rw-r----- 1 root root 9665 Dec 29 14:40 vendor/bundle/ruby/2.7.0/gems/google-ads-googleads-15.0.0/lib/google/ads/google_ads/google_ads_client.rb
> ```
> 
> Manually setting these permissions fixes the issue, but this isn't the ideal way. The same issue has been reported with another gem - [googleads/google-api-ads-ruby#89](https://github.com/googleads/google-api-ads-ruby/issues/89)

To correct - there are no read permissions which have to be explicitly defined after installing the gem

**Comment by mcloonan** [comment]
Thanks for the extra info. We'll take a look at this.

**Comment by abraham** [comment]
Please give [v16.0.0](https://github.com/googleads/google-ads-ruby/releases/tag/google-ads-googleads%2Fv16.0.0) a try. Read permissions are now added when building the gem.

**Comment by mcloonan** [comment]
Closing for now. Please re-open if there are any further permission issues.
