### ISSUE TITLE
When will be Google Ads v9 supported

### ISSUE THREAD

**Issue by ondrejbartas** [googleads/google-ads-ruby#357]
Hello, 

yesterday new version of Google Ads API was released, when we are going to be able to use it?

Thanks

**Comment by mcloonan** [comment]
Likely sometime next week. This is the normal release cadence for new releases and this client library. Whenever a new API version is released, you can expect the ruby library to be released the following week.

**Comment by ondrejbartas** [comment]
Great @mcloonan thank you for your reply 👍
