### ISSUE TITLE
"The error code is not in this version" during create custom conversion goal

### ISSUE THREAD

**Issue by mcm66103** [googleads/google-ads-ruby#371]
**Describe the bug:**
I am trying to create a custom conversion goal. I receive an error message that the request contains an invalid argument and the error code is not in this version.

**Steps to Reproduce:**
ruby: `2.6.8`
gem: `15.0.0`

```
ga = GoogleAds.new # class we use to get the client.
# ga.client = Google::Ads::GoogleAds::GoogleAdsClient.new("path/to/config.rb")

garf = ::Google::Protobuf::RepeatedField.new(:string)
garf += ["customers/<ID>/conversionActions/708226787"]

custom_conversion_goal = ga.client.resource.custom_conversion_goal do |ccg|
  ccg.name = "20211228 test custom conversion goal" 
  ccg.conversion_actions = garf
  ccg.status = :ENABLED  
end

o = ga.client.operation.custom_conversion_goal
o.create = custom_conversion_goal

ga.client.service.custom_conversion_goal.mutate_custom_conversion_goals(
  customer_id: "<ID>",
  operations: [o]
)

>calling googleads.googleapis.com:/google.ads.googleads.v9.services.CustomConversionGoalService/MutateCustomConversionGoals
Failing with status #<struct Struct::Status code=3, details="Request contains an invalid argument.", metadata={"google.ads.googleads.v9.errors.googleadsfailure-bin"=>"\n>\n\x02\b\x01\x12&The error code is not in this version.\"\x10\x12\x0E\n\noperations\x18\x00\x12\x16t7rKdS-18bqIXxL208I_7g", "grpc-status-details-bin"=>"\b\x03\x12%Request contains an invalid argument.\x1A\x9F\x01\nCtype.googleapis.com/google.ads.googleads.v9.errors.GoogleAdsFailure\x12X\n>\n\x02\b\x01\x12&The error code is not in this version.\"\x10\x12\x0E\n\noperations\x18\x00\x12\x16t7rKdS-18bqIXxL208I_7g", "request-id"=>"t7rKdS-18bqIXxL208I_7g"}, debug_error_string="{\"created\":\"@1640722058.936044000\",\"description\":\"Error received from peer ipv4:172.217.165.42:443\",\"file\":\"src/core/lib/surface/call.cc\",\"file_line\":1069,\"grpc_message\":\"Request contains an invalid argument.\",\"grpc_status\":3}">
CID: <CID>, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v9.services.CustomConversionGoalService/MutateCustomConversionGoals, IsFault: yes, Request ID: t7rKdS-18bqIXxL208I_7g
Google::Ads::GoogleAds::Errors::GoogleAdsError: Google::Ads::GoogleAds::Errors::GoogleAdsError
from /usr/local/bundle/gems/google-ads-googleads-15.0.0/lib/google/ads/google_ads/interceptors/error_interceptor.rb:67:in `rescue in request_response'
Caused by GRPC::InvalidArgument: 3:Request contains an invalid argument.. debug_error_string:{"created":"@1640722058.936044000","description":"Error received from peer ipv4:172.217.165.42:443","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Request contains an invalid argument.","grpc_status":3}
from /usr/local/bundle/gems/grpc-1.41.1-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:29:in `check_status'
```
**Expected behavior:**
I would expect this to create a custom conversion goal or I would expect the error message to be in this version of the API.

**Client library version and API version:**
Client library version: 15.0.0
Google Ads API version: V9

**Comment by xflesym** [comment]
Hi Rick,

I've tried with your code snippets here with my own account and it is working fine for me without issues, with same client lib version 15.0.0.

So this doesn't seem to be a ruby client lib specific issue. Please double check that the account you are using is a production account, not a test account, as some features may not be available on test account.

If the issue remains, please send a full request/response log to our support team googleadsapi-support@google.com and we will take a look into why the error happens.

Thanks,
-Fei

**Comment by mcm66103** [comment]
I am trying to make the same API call with production credentials and I am getting the same result. Can you detail any differences between your successful API call and the API call as described above?

**Comment by mcm66103** [comment]
Additionally, are there any limitations about what sorts of conversion actions can be used in a custom conversion goal? I do not see any limitations as described by the documentation.

I have reached out to googleadsapi-support@google.com regarding the issue.

**Comment by xflesym** [comment]
The API call doesn't show any noticeable differences, as I was using the exact code as yours. I am also not aware of any limitations on conversion action types used in conversion goals. This sounds like an edge case / bug. Please follow up with googleadsapi-support@google.com and re-open if ruby specific issues are discovered.
