### ISSUE TITLE
grcp dependency in the latest version is generating this error "missing symbol called" message

### ISSUE THREAD

**Issue by LuceroNava1** [googleads/google-ads-ruby#373]
**Describe the bug:**
We get a error when we use the google ads gem: "missing symbol called". 

**Steps to Reproduce:**
grpc - 1.42.0
language - ruby
MacBook Pro (15-inch, 2019)
Processor 2.6 GHz 6-Core Intel Core i7
Ruby - 3.0.0, 3.0.3
![imagen](https://user-images.githubusercontent.com/39096530/148113909-eaf07737-ddd4-4896-b820-42fee6621400.png)
```
[shoppingcontent.googleapis.com] GET /content/v2.1/522447824/accounts/522447824 (0.370 s)
dyld[5807]: missing symbol called
```

the grcp dependency in the latest version is generating this error
https://github.com/grpc/grpc/issues/28271#

**Expected behavior:**
![imagen](https://user-images.githubusercontent.com/39096530/148114917-6c518d7d-e7e4-4679-9241-b953b91f82b1.png)
```
[shoppingcontent.googleapis.com] PUT /content/v2.1/513198309/accounts/513198309 (0.290 s)
CID: 9825386996, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v8.services.MerchantCenterLinkService/ListMerchantCenterLinks, IsFault: no, Request ID: 4TNRz_cjq1riVq8WNZVbwQ
Outgoing request: Headers: {"developer-token":"REDACTED","login-customer-id":"9945936419","x-goog-api-client":"gl-ruby/3.0.3 gax/0.4.3 gapic/13.0.0 grpc/1.41.0","x-goog-request-params":"customer_id=9825386996"} Payload: {"customerId":"9825386996"}
Incoming response: Payload: {"merchantCenterLinks":[{"resourceName":"customers/9825386996/merchantCenterLinks/513198309","id":"513198309","merchantCenterAccountName":"MACHA-TEST-ACCOUNT","status":"PENDING"}]}
CID: 9825386996, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v8.services.MerchantCenterLinkService/MutateMerchantCenterLink, IsFault: no, Request ID: Q1oZaXTA9PRPPX_AvIGMWg
Outgoing request: Headers: {"developer-token":"REDACTED","login-customer-id":"9945936419","x-goog-api-client":"gl-ruby/3.0.3 gax/0.4.3 gapic/13.0.0 grpc/1.41.0","x-goog-request-params":"customer_id=9825386996"} Payload: {"customerId":"9825386996","operation":{"updateMask":"status","update":{"resourceName":"customers/9825386996/merchantCenterLinks/513198309","status":"ENABLED"}}}
```
Incoming response: Payload: {"result":{"resourceName":"customers/9825386996/merchantCenterLinks/513198309"}}
**Client library version and API version:**
Client library version: GRPC 1.42.0
Google Ads API version: 14, 15

google-ads-googleads (14.0.0), 15
grpc (1.42.0)
google-protobuf (~> 3.18)
**Request/Response Logs:**

This error causes the application to stop by rails and our application locally.
**Anything else we should know about your project / environment:**

at this moment we have forced to use the previous grpc version (grpc 1.41.0), and the google-ads-googleads version (13), to continue working on our project.

**Comment by diegocharles** [comment]
I'm getting the same error and I'm stuck on this.

**Comment by mcloonan** [comment]
Looks like an issue with grpc. You should either downgrade to 1.41, wait for a new version that fixes this, or possibly try this workaround from the grpc repo: https://github.com/grpc/grpc/issues/28271#issuecomment-1007677177

Our gem doesn't pin a specific version of grpc, and our dependencies only require `grpc ~> 1.36`, so you should be able to fall back to 1.41 with no issues.
