### ISSUE TITLE
Example on Remove CampaignCriterion Operation

### ISSUE THREAD

**Issue by eftikharEmad** [googleads/google-ads-ruby#375]
Hello Team,
we are migrating our code from AdWords API to Google Ads API, every thing is going very well except one api, remove list of `CampaignCriterion`.

following `MutateCampaignCriteriaRequest` and `CampaignCriterionOperation` in this [link ](https://developers.google.com/google-ads/api/reference/rpc/v9/CampaignCriterionOperation) I was able to build a code block to remove criterions, check 
```
client = Google::Ads::GoogleAds::GoogleAdsClient.new
operations =[]
ids = [1018308, 9054868].each do |id|
  operations << client.operation.remove_resource.campaign_criterion(id.to_s)
end

response = client.service.campaign_criterion.mutate_campaign_criteria(
  customer_id: customer_id.to_s,
  operations: operations
)
```
but I keep getting this error :
```
/generic/active_call.rb:29:in `check_status': 3:Request contains an invalid argument.. debug_error_string:{"created":"@1643560561.052611000","description":"Error received from peer ipv4:142.251.37.42:443","file":"src/core/lib/surface/call.cc","file_line":1064,"grpc_message":"Request contains an invalid argument.","grpc_status":3}
```

I can't find direct example on this, can you please advise and let me know if I am missing any thing ?

**Comment by eftikharEmad** [comment]
oops I just tried the next 
```
operations << client.operation.remove_resource.campaign_criterion("customers/#{customer_id}/campaignCriteria/#{campaign_id}~#{criterion_id}")
```
and actually did work 😅  , but still criterions returned on the get request

**Comment by mcloonan** [comment]
Glad you figured it out.

As a tip, we have a helper for constructing resource names. So instead of what you did, you could use `client.path.campaign_criterion(customer_id, campaign_id, criterion_id)`
