### ISSUE TITLE
Service account: missing required authentication credential

### ISSUE THREAD

**Issue by Bukenco** [googleads/google-ads-ruby#379]
Does this work for service accounts? Even all configurations are done correctly, it throws the error: " GRPC::Unauthenticated: 16:Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential"

**Comment by mcloonan** [comment]
I've tested with service accounts and had it work. Can you share your config file setup (minus any sensitive information)?

**Comment by Bukenco** [comment]
`Google::Ads::GoogleAds::Config.new do |c|
  c.treat_deprecation_warnings_as_errors = false
  c.warn_on_all_deprecations = false
  c.developer_token = 'developer_token'

  c.keyfile = '/home/keys.json'
  c.impersonate = 'impersonate_email@email.iam.gserviceaccount.com'
  c.login_customer_id = 12345678
  c.log_level = 'WARN'
end`

**Comment by joshfester** [comment]
@Bukenco did you ever find a solution? I'm running into this same issue with a service account

**Comment by Bukenco** [comment]
@joshfester Unfortunately no. We had to create our solution tailored to our requirements
