### ISSUE TITLE
Alpine Error loading shared library ld-linux-x86-64.so.2: No such file or directory

### ISSUE THREAD

**Issue by TechnologyHypofriend** [googleads/google-ads-ruby#386]
**Describe the bug:**
Unable to use this gem on Alpine Linux

/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require': Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/local/bundle/gems/grpc-1.45.0-x86_64-linux/src/ruby/lib/grpc/3.0/grpc_c.so) - /usr/local/bundle/gems/grpc-1.45.0-x86_64-linux/src/ruby/lib/grpc/3.0/grpc_c.so (LoadError)

**Steps to Reproduce:**
require 'google/ads/google_ads'

**Expected behavior:**
library should be loaded

**Client library version and API version:**
Client library version: latest
Google Ads API version: latest

**Comment by mcloonan** [comment]
This looks like an error loading grpc because of one of its dependencies, so you'd probably have better luck filing this bug there: https://github.com/grpc/grpc/tree/master/src/ruby
