### ISSUE TITLE
incompatible architecture (have 'x86_64', need 'arm64e')

### ISSUE THREAD

**Issue by touseefmurtaza** [googleads/google-ads-ruby#388]
## Description

LoadError: dlopen(/Users/touseef/.rvm/gems/ruby-3.0.1@core-api/gems/grpc-1.45.0-universal-darwin/src/ruby/lib/grpc/3.0/grpc_c.bundle, 0x0009): tried: '/Users/touseef/.rvm/gems/ruby-3.0.1@core-api/gems/grpc-1.45.0-universal-darwin/src/ruby/lib/grpc/3.0/grpc_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')) - /Users/touseef/.rvm/gems/ruby-3.0.1@core-api/gems/grpc-1.45.0-universal-darwin/src/ruby/lib/grpc/3.0/grpc_c.bundle

**Describe the bug:**
I have an M1 machine and after installing the `google-ads-googleads` gem I started getting the incompatibility error.

**Steps to Reproduce:**
- Include the gem in Gemfile

**Comment by simonknoll** [comment]
A workaround until https://github.com/grpc/grpc/issues/31215 is fixed is, to add the following to your Gemfile:

`gem "grpc", '~> 1.41.0'`

as 1.41 is the last grpc version compiling on m1 macs
