### ISSUE TITLE
GoogleAdsError never raised in v1.0

### ISSUE THREAD

**Issue by javoeria** [googleads/google-ads-ruby#39]
After the v1.0 update, a query with wrong arguments should expect the next error: `Google::Ads::GoogleAds::Errors::GoogleAdsError`
But it never raised and, instead, it raises a `GRPC::InvalidArgument` error.
Is this correct? Thanks.

**Comment by mcloonan** [comment]
I believe this is fixed now. It was an error with the logging interceptor.

**Comment by javoeria** [comment]
I just checked again and it's still happening

**Comment by javoeria** [comment]
A month later and the same problem continues...
