### ISSUE TITLE
GRPC::Unimplemented error when trying to run example

### ISSUE THREAD

**Issue by tylerjchrestoff** [googleads/google-ads-ruby#390]
I am receiving a GRPC::Unimplemented error when trying to run the examples provided by the repository. I have configured my client with logging enabled with target `STDOUT` and level `DEBUG`. Am I doing something wrong or missing a step in authentication or is this a broader scope error with the Ads API itself? I'm able to find 2 other instances of people receiving a similar error  but no replies with solutions.

Here is the full output of a call to a `.get_campaigns` method implemented similar to the example:
```
Running via Spring preloader in process 38731
Loading development environment (Rails 6.0.3.7)
irb(main):001:0> GoogleAdsService.get_campaigns
I, [2022-04-20T15:50:46.870469 #38731]  INFO -- : CID: 938-016-4633, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v6.services.GoogleAdsService/SearchStream, IsFault: no
W, [2022-04-20T15:50:47.617466 #38731]  WARN -- : CID: 938-016-4633, Host: googleads.googleapis.com:443, Method: /google.ads.googleads.v6.services.GoogleAdsService/SearchStream, IsFault: yes
I, [2022-04-20T15:50:47.617900 #38731]  INFO -- : Outgoing request: Headers: {"developer-token":"REDACTED","x-goog-api-client":"gl-ruby/2.7.4 gax/0.3.4 gapic/10.0.0 grpc/1.45.0","x-goog-request-params":"customer_id=938-016-4633"} Payload: {"customerId":"938-016-4633","query":"SELECT campaign.id, campaign.name FROM campaign ORDER BY campaign.id"}
I, [2022-04-20T15:50:47.618218 #38731]  INFO -- : Incoming response (errors):
  GRPC::Unimplemented(12:Operation is not implemented, or supported, or enabled.. debug_error_string:{"created":"@1650484247.617206000","description":"Error received from peer ipv6:[2607:f8b0:4004:c09::5f]:443","file":"src/core/lib/surface/call.cc","file_line":906,"grpc_message":"Operation is not implemented, or supported, or enabled.","grpc_status":12}):
  called from: /Users/tylerchrestoff/code/data-warehouse/app/services/google_ads_service.rb:67:in `each'
Traceback (most recent call last):
        4: from (irb):1
        3: from app/services/google_ads_service.rb:67:in `get_campaigns'
        2: from app/services/google_ads_service.rb:67:in `each'
        1: from app/services/google_ads_service.rb:67:in `each'
GRPC::Unimplemented (12:Operation is not implemented, or supported, or enabled.. debug_error_string:{"created":"@1650484247.617206000","description":"Error received from peer ipv6:[2607:f8b0:4004:c09::5f]:443","file":"src/core/lib/surface/call.cc","file_line":906,"grpc_message":"Operation is not implemented, or supported, or enabled.","grpc_status":12})
irb(main):002:0>
```

The method is defined in a Ruby module as:
```ruby
def self.get_campaigns
  responses = client.service.google_ads.search_stream(
    :customer_id => CUSTOMER_ID,
    :query => "SELECT campaign.id, campaign.name FROM campaign ORDER BY campaign.id"
  )

  responses.each do |response|
    response.results.each do |row|
      puts "Campaign with ID #{row.campaign.id} and name '#{row.campaign.name}' was found."
    end
  end
end
```

**Comment by mcloonan** [comment]
I just ran the code you provided and it worked fine.

What version of the grpc gem are you using?

**Comment by tylerjchrestoff** [comment]
`grpc (1.45.0)` from Gemfile.lock.

**Comment by tylerjchrestoff** [comment]
Any suggestions here? I am still stuck and Google Ads API support was not able to help and redirected me back here.

**Comment by mcloonan** [comment]
That's a newer version of grpc than I was using, so maybe try going back to 1.43. If that doesn't fix it, then I would suggest trying with a completely new environment and see if you can reproduce there. If so, then it might be something to do with your system. If not, then you can start looking at differences between the two environments until you find the culprit.

I can't reproduce this error, so it's hard for me to try to debug. You may also try filing an issue on the GRPC repo directly since it seems to be an issue with one of our dependencies and not with our library directly.

**Comment by tylerjchrestoff** [comment]
Thanks for the reply. I'll try setting up in a new environment.

`1.45.0` is what's installed by default when including the gem in the Gemfile without any other specifications, so I'd be surprised if that's the issue.

**Comment by Pablo251** [comment]
I was having a similar issue with GRPC (**RPC::Unimplemented: 12:GRPC target method can't be resolved)** and updating the google-ads gem to the current last version (16.0.0) ended up fixing the issue.


The previous version was installed by default under  10.0.0 and after found that it make use of the v6 version of google api and it is deprecated then I just had to update the gem to the last stable version and worked.

**Comment by mcloonan** [comment]
Now that I see that explanation, it makes perfect sense. I didn't even consider the case where you were trying to use a deprecated version of the Google Ads API. That's very likely what @tylerjchrestoff was encountering as well. Can you try upgrading to a new version of the google-ads-googleads gem and let me know if it persists?

**Comment by tylerjchrestoff** [comment]
That was my issue. `bundle install` was not cutting it. After getting a successful `bundle update` off, everything started to work as expected.

Thanks for the help!
