### ISSUE TITLE
NoMethodError on list_accessible_customers example

### ISSUE THREAD

**Issue by diegosaul402** [googleads/google-ads-ruby#394]
**Describe the bug:**
I'm upgrading from v13 to v17 and I see I'm having issues adapting my code from changes implemented on v16 that implement changes [from API v10](https://developers.google.com/google-ads/api/docs/release-notes#v10) if I'm not mistaken.
I see that on v16 following API v10 [get methods](https://developers.google.com/google-ads/api/docs/release-notes#all_services) has been removed. I'm just not sure how to adapt the [list accessible customers](https://github.com/googleads/google-ads-ruby/blob/main/examples/account_management/list_accessible_customers.rb) example.
The example is outdated because i'm getting this error
```
> client.service.customer.list_accessible_customers.resource_names
   NoMethodError (undefined method `get_customer' for # 
   <Google::Ads::GoogleAds::V10::Services::CustomerService::Client::Configuration::Rpcs:0x00007fa246236f00
```

I already tried with
```
> client.service.google_ads.search(query: query)
  Incoming response (errors):
  Google::Ads::GoogleAds::Errors::GoogleAdsError(Google::Ads::GoogleAds::Errors::GoogleAdsError): Invalid customer ID ''.
```
which makes sense because I don't have any customer_id to send

Any ideas how to adapt this call?

**Comment by mcloonan** [comment]
I don't think the example itself is outdated; I just tested and it worked fine for me.

It sounds like what you're actually asking is: what to do with the resource names once you have them, to get more details about the customer? You can extract the customer ID from the resource name (the standard format for most resource names is `customers/[customer_id]/whateverResource/resource_id`) and then supply that customer ID in the GoogleAdsService.Search request along with a query to get whatever fields you want.

If this doesn't help, I suggest reaching out on our product support forum for assistance since this doesn't appear to be a Ruby-specific question: https://groups.google.com/g/adwords-api

**Comment by diegosaul402** [comment]
Thank you for the quick answer @mcloonan 
This code has been working for me for months until today when I updated this gem, that's why I think it could be a breaking change. 
The problem I'm facing is the `NoMethodError` when `client.service.customer` runs, I don't even get to call `list_accessible_customers` on the chain and I never get the resource names. Nothing else has changed on my codebase. But if you can confirm this is the right way to retrieve the accessible accounts and it's updated I'll be testing this code in other environments.

**Comment by mcloonan** [comment]
Oh, that is weird. Just attempting to fetch the service results in `undefined method get_customer`? I wouldn't expect that to happen unless some code somewhere tried to call that method. Are you sure there's no code somewhere that's trying to call that method. I can't reproduce this behavior locally; the service works fine for me. I reinstalled the gem just now to double-check.

Is there more to the stack trace than what you pasted initially? Can you share a bigger code snippet of what you're trying to do so I can try to reproduce?

**Comment by mcloonan** [comment]
Also, to be clear, `get_customer` was supported before v10, and was removed in v10, so if you have code that is trying to call that method, then this behavior change is expected. But if you aren't actually using that method and are still getting this error, then that's concerning.

**Comment by diegosaul402** [comment]
From my understanding, calling `client.service.customer` [from the example](https://github.com/googleads/google-ads-ruby/blob/0df9947436fc813b520a13a83e4ae91816a8a5d8/examples/account_management/list_accessible_customers.rb#L34) calls `get_customers` under the good. That's what is crashing for me.
This is the bigger trace
```
NoMethodError (undefined method `get_customer' for #<Google::Ads::GoogleAds::V10::Services::CustomerService::Client::Configuration::Rpcs:0x00007ff0346528a0 @mutate_customer=#<Gapic::Config::Method:0x00007ff034652850 @parent_config=#<Gapic::Config::Method:0x00007ff0318d5260>, @retry_policy={:retry_codes=>[4]}>, @list_accessible_customers=#<Gapic::Config::Method:0x00007ff034652800 @parent_config=#<Gapic::Config::Method:0x00007ff0318d5198>, @retry_policy={:retry_codes=>[4]}>, @create_customer_client=#<Gapic::Config::Method:0x00007ff0346527b0 @parent_config=#<Gapic::Config::Method:0x00007ff0318d5120>, @retry_policy={:retry_codes=>[4]}>>):

app/services/API/google_service_handler.rb:43:in `block (2 levels) in configure_services'
app/services/API/google_service_handler.rb:42:in `block in configure_services'
app/services/API/google_service_handler.rb:41:in `each'
app/services/API/google_service_handler.rb:41:in `configure_services'
app/services/API/google_service_handler.rb:33:in `method_missing'
```

**Comment by mcloonan** [comment]
I'm not sure what `google_service_handler.rb` is. It's not part of our library. And our library does not call `get_customers` as part of the initialization. So I would dig into where that `google_service_handler.rb` is coming from and remove that from your environment and try again.

**Comment by diegosaul402** [comment]
True, I failed to realize that file was ours. I added that back when the service will retry forever if a wrong refresh token were provided. I removed the unauthorized error code from retry_codes. 

I'll fix that and I'll come back with updates, thank you for helping me @mcloonan !
