### ISSUE TITLE
How to remove linking between manager and client accounts

### ISSUE THREAD

**Issue by diegosaul402** [googleads/google-ads-ruby#398]
**What is your question?**

I'm trying to remove the linking between a manager account and a client account.
I can't find a specific example to do it, so I'm following the API's docs.
This is what I'm trying to do:
### 1. Get the customer_client_link resource_name
I'm able to use `search` to get the customer_client_link for the accounts I'm trying to remove the linking from. 
This is the query I use:
```
SELECT customer_client_link.resource_name
FROM customer_client_link
WHERE customer_client_link.client_customer = 'customers/CHILD_CUSTOMER_ID'
```
I end up with a string like this one after getting the `resource_name` from the query result:
```
customers/{customer_id}/customerClientLinks/{client_customer_id}~{manager_link_id}
```
### 2. Create the [CustomerClientLinkOperation](https://developers.google.com/google-ads/api/reference/rpc/v11/CustomerClientLinkOperation)
```ruby
def client_link_operation(customer_link)
      client_link = client.resource.customer_client_link do |link|
        link.resource_name = customer_link
      end

      client.operation.update_resource.customer_client_link(client_link) do |link|
        link.status = :INACTIVE
      end
end
```
where `customer_link` is the string I got on step 1.

### 3. Execute a mutate operation
```ruby
client.service.customer_client_link.mutate_customer_client_link(customer_id: manager_id,
                                                                               operations: update_operations)
```
where 
- `manager_id` is the manager account ID
- `update_operations` is the result from the `client_link_operation` method

`update_operations` looks like this
```ruby
<Google::Ads::GoogleAds::V11::Services::CustomerClientLinkOperation: update_mask: <Google::Protobuf::FieldMask: paths: ["status"]>, update: <Google::Ads::GoogleAds::V11::Resources::CustomerClientLink: resource_name: "customers/xxxxxxxx/customerClientLinks/xxxxxxxx~xxxxxxxx", status: :INACTIVE>>
```

### The error
When I run `mutate_customer_client_link` I get the following exception
```ruby
<ArgumentError: unknown field operations>
```
Not sure what I'm doing wrong. I know that the mutate operation never runs and my code never hits the API, this seems to be an input validation but not sure what I'm doing wrong or how to fix it, any ideas on how to accomplish this?

**Comment by mcloonan** [comment]
It looks like the field is called `operation` in the docs (https://developers.google.com/google-ads/api/reference/rpc/v11/MutateCustomerClientLinkRequest?hl=en#operation) and in our lib as well (https://github.com/googleads/google-ads-ruby/blob/main/lib/google/ads/google_ads/v11/services/customer_client_link_service_pb.rb#L17).

I'm honestly not sure how you go tit working calling the field `operations`.

In any case, there is no way to perform more than one of this type of operation in a single request. You'll have to make a separate request per operation.
