### ISSUE TITLE
Feature Request: provide with intermediate objects to avoid client global

### ISSUE THREAD

**Issue by apneadiving** [googleads/google-ads-ruby#40]
For now, pretty much everything is attached to the client for "convenience" sake.

Yet as a developer, I would not like to need a client object to build the operations: in the end its more a global value than a convenient one.

Basically I would like to be able to create an operation, use an enum, use wrappers without the client.

For instance:
```
# in addition of 
client = ::Google::Ads::GoogleAds::GoogleAdsClient.new
client.operation(name)
# I'd like to be able to use
::Google::Ads::GoogleAds::GoogleAdsClient.operation(name, version)
# or maybe something like
proto_lookup = ::Google::Ads::GoogleAds::ProtoLookup.new(version)
proto_lookup.operation(name)
```
Indeed, creating an operation should not rely on some api configuration triggered during client instantiation.

One way to achieve this would be to have `proto_lookup_utils` at the class level. 

Another way would be to move lookup utils in an independent object.

Would you accept either move?

**Comment by apneadiving** [comment]
the `ProtoLookup` would be the easiest way to proceed, I could suggest a pull request if I have a green

**Comment by mcloonan** [comment]
Thanks for implementing this!
