### ISSUE TITLE
Do not restrict minor version of `gapic-common` to 0.6.x

### ISSUE THREAD

**Issue by kristofferek** [googleads/google-ads-ruby#403]
**Describe the bug:**

This gem has a strict dependency of the `gapic-common` gem on the minor version 0.6.x, i.e. https://github.com/googleads/google-ads-ruby/blob/afa41190a2c0646f511221a1746f365b90173649/google-ads-googleads.gemspec#L37. I don't see why it would be necessary to restrict the minor version of this gem. This is preventing us from updating other gems that depends on a higher minor version than 0.6 of the `gapic-common` gem. For example, the latest release of the [google-analytics-admin-v1alpha](https://github.com/googleapis/google-cloud-ruby/tree/main/google-analytics-admin-v1alpha) gem has the following dependency `"gapic-common", ">= 0.10", "< 2.a"`. The strict dependency of this gem prevents us from using the latest version of the `google-analytics-admin-v1alpha` gem.

**Steps to Reproduce:**

...

**Expected behavior:**

I would expect there to only be a dependency on the major version, i.e. `'gapic-common', '~> 0.6'`

**Comment by mcloonan** [comment]
Agree. I'll update this with our next release. Thanks for pointing it out!
