### ISSUE TITLE
Unable to use ProtoLookupUtil in v19

### ISSUE THREAD

**Issue by alexibz** [googleads/google-ads-ruby#415]
**Describe the bug:**
I'm unable to use the [ProtoLookupUtil](https://developers.google.com/google-ads/api/docs/client-libs/ruby/lookup-util) in v19.0.0.

**Steps to Reproduce:**
```ruby
campaign = client.resource(:Campaign)
ArgumentError: wrong number of arguments (given 1, expected 0)
from /home/xxx/gems/google-ads-googleads-19.0.0/lib/google/ads/google_ads/google_ads_client.rb:160:in `resource'
```
**Expected behavior:**
```
campaign = Google::Ads::GoogleAds::V11::Resources::Campaign.new
```
**Client library version and API version:**
Client library version:  v19.0.0
Google Ads API version: V11

**Comment by mcloonan** [comment]
That's a very old syntax that I didn't think we'd supported for some time.

Can you try:

    campaign = client.resource.campaign

**Comment by alexibz** [comment]
Worked great for

```ruby
c.resource.google_ads_error
c.resource.campaign
```

I will `Send feedback` on the Google Ads API page to have it updated.
