### ISSUE TITLE
Unable to remove final_url for a CallAd

### ISSUE THREAD

**Issue by jmbeck** [googleads/google-ads-ruby#423]
**Describe the bug:**
In the Google Ads dashboard, I am able to remove the final url manually.  Via the Google Ads API this doesn't work.

**Steps to Reproduce:**
```
ad_operation = GOOGLE_ADS_CLIENT.operation.update_resource.ad(ad_resource_name) do |adwords_ad|
  adwords_ad.final_urls << ''
end

response = GOOGLE_ADS_CLIENT.service.ad.mutate_ads(
  customer_id: @customer_id,
  operations: [ad_operation],
)
```

I tried a few different alternatives:
```
  adwords_ad.final_urls << ''
  adwords_ad.final_urls << nil
  adwords_ad.final_urls = []
  #also omitting this line and updating other fields
```

**Expected behavior:**
If omitted or set to an empty string, the final_url should be removed from the call ad.

**Client library version and API version:**
Client library version: 20.0.0
Google Ads API version: v12
```
DEPENDENCIES
  ...
  google-ads-googleads (~> 20.0.0)
```

**Request/Response Logs:**
Response:
```
/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/grpc-1.50.0-x86_64-darwin/src/ruby/lib/grpc/generic/active_call.rb:29:in `check_status': 3:Request contains an invalid argument.. debug_error_string:{UNKNOWN:Error received from peer ipv4:142.250.189.170:443 {created_time:"2023-01-06T11:39:45.309568-08:00", grpc_status:3, grpc_message:"Request contains an invalid argument."}} (GRPC::InvalidArgument)
```

**Anything else we should know about your project / environment:**

**Comment by mcloonan** [comment]
Have you tried manually updating the field mask: https://developers.google.com/google-ads/api/docs/client-libs/ruby/field-masks

**Comment by jmbeck** [comment]
Thank you @mcloonan, that solves it!  If anyone else sees this, it was as simple as adding this line: 
```ad_operation.update_mask.paths << 'final_urls'```
