### ISSUE TITLE
Campaign#bidding_strategy_type= (and other read-only field writers) should not be defined

### ISSUE THREAD

**Issue by fables-tales** [googleads/google-ads-ruby#44]
`campaign.bidding_strategy_type = :MANUAL_CPC` is possible but if submitted as part of a write operation it will fail because bidding_strategy_type is read only. We get back a very confusing error message

```
/Users/samphippen/.gem/ruby/2.5.3/gems/google-gax-1.5.0/lib/google/gax/api_callable.rb:369:in `rescue in block in retryable': GaxError Exception occurred in retry method that was not classified as transient, caused by 3:Request contains an invalid argument. (Google::Gax::RetryError)
```

Ideally, it would be impossible to call `Campaign#bidding_strategy_type=` to prevent this from happening. It should be possible to define methods as read only in the protos.

**Comment by mcloonan** [comment]
I think this is more a bug for the gax and/or grpc team than for this lib. Can you look into filing a feature request with them?

**Comment by apneadiving** [comment]
just came across this by accident and I can tell it is very misleading: I have to change my implementation.

Yet I am confused: how to set the bid strategy then? Thanks

**Comment by mcloonan** [comment]
You should be able to set any of the `one_of` fields under `campaign_bidding_strategy`. See: https://github.com/googleads/google-ads-ruby/blob/master/lib/google/ads/google_ads/v1/resources/campaign_pb.rb#L58

For example, `campaign.target_cpa = x`.

The bidding_strategy_type is a read only field you can use to determine the type after it's added.
