### ISSUE TITLE
Google::Ads::GoogleAds::Errors::GoogleAdsError: Google::Ads::GoogleAds::Errors::GoogleAdsError

### ISSUE THREAD

**Issue by JohanAlvarado** [googleads/google-ads-ruby#442]
**Describe the bug:**
`Google::Ads::GoogleAds::Errors::GoogleAdsError:` Google::Ads::GoogleAds::Errors::GoogleAdsError`

**Steps to Reproduce:**

**Expected behavior:**

**Client library version and API version:**
Client library version: 
Google Ads API version: 22.1

**Request/Response Logs:**
Google::Ads::GoogleAds::Errors::GoogleAdsError: Google::Ads::GoogleAds::Errors::GoogleAdsError
/usr/local/bundle/gems/google-ads-googleads-22.1.0/lib/google/ads/google_ads/interceptors/error_interceptor.rb:67:in `rescue in request_response': Google::Ads::GoogleAds::Errors::GoogleAdsError (Google::Ads::GoogleAds::Errors::GoogleAdsError)
	
from /usr/local/bundle/gems/google-ads-googleads-22.1.0/lib/google/ads/google_ads/interceptors/error_interceptor.rb:63:in `request_response'
	
from /usr/local/bundle/gems/grpc-1.54.0-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:175:in `intercept!'
	
from /usr/local/bundle/gems/grpc-1.54.0-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:177:in `block in intercept!'
	
from /usr/local/bundle/gems/google-ads-googleads-22.1.0/lib/google/ads/google_ads/interceptors/logging_interceptor.rb:53:in `request_response'
	
from /usr/local/bundle/gems/grpc-1.54.0-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:175:in `intercept!'
	
from /usr/local/bundle/gems/grpc-1.54.0-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:173:in `block in request_response'
	
from /usr/local/bundle/gems/gapic-common-0.9.0/lib/gapic/grpc/service_stub/rpc_call.rb:121:in `call'
	
from /usr/local/bundle/gems/gapic-common-0.9.0/lib/gapic/grpc/service_stub.rb:156:in `call_rpc'
	
from /usr/local/bundle/gems/google-ads-googleads-22.1.0/lib/google/ads/google_ads/v13/services/google_ads_service/client.rb:261:in `search'
	
from /usr/local/bundle/gems/google-ads-googleads-22.1.0/lib/google/ads/google_ads/service_wrapper.rb:50:in `public_send'
	
from /usr/local/bundle/gems/google-ads-googleads-22.1.0/lib/google/ads/google_ads/service_wrapper.rb:50:in `method_missing'

**Anything else we should know about your project / environment:**

**Comment by mcloonan** [comment]
Can you provide some steps to reproduce if this is still ongoing? The error message by itself doesn't give enough information to go on.
