### ISSUE TITLE
Update customer attribute using CustomerService

### ISSUE THREAD

**Issue by eftikharEmad** [googleads/google-ads-ruby#447]
Hello,

I hopefully can get answers here, I am working on auto-tagging and try to make the setup stage is done automatically means:
updating the `auto_tagging_enabled` attribute should be done via and API request and then create a ConversionAction also via an API.
I checked google group for an example but they advised me to ask you, https://groups.google.com/g/adwords-api/c/aRx8f_7Nd6A 
So , is this doable using the ruby gem because I cant find the endpoint to use https://github.com/googleads/google-ads-ruby/tree/main/examples/

Thanks in advance

**Comment by mcloonan** [comment]
We don't have an exact example for updating a Customer, but you can look at another [update example](https://github.com/googleads/google-ads-ruby/blob/main/examples/campaign_management/update_campaign_criterion_bid_modifier.rb) for an idea of how updates are performed in the Ruby Library, and look at the [customer](https://developers.google.com/google-ads/api/reference/rpc/v14/Customer) documentation for a list of fields that you could modify on it.

We can't exhaustively have examples for every individual resource type, but you should be able to piece together what you need using a combination of the examples we do have and the reference documentation, in general.

If you have questions, please reach back out to the main support channel that led you here.

**Comment by eftikharEmad** [comment]
Thank you so much
