### ISSUE TITLE
Regarding gem installation in Ruby 2.3.0

### ISSUE THREAD

**Issue by div927** [googleads/google-ads-ruby#456]
Hello

I'm not able to install this gem in Ruby 2.3.0 is there any alternate way to use it without upgrading my Ruby version? I want to use this `generate_historical_metrics`

**Comment by mcloonan** [comment]
We only officially support the most recent versions that are still supported officially by Ruby. You can generally check which versions are supported on their download page: https://www.ruby-lang.org/en/downloads/

Sometimes our library may still work on older versions of Ruby, but in those cases your use is at your own risk and we would ask you to upgrade to a newer version if you encounter any version-specific issues.
