### ISSUE TITLE
Wrong dependency of gapic-common

### ISSUE THREAD

**Issue by himanshu-patel-dev** [googleads/google-ads-ruby#484]
**Describe the bug:**
gem `google-ads-googleads` version `27.0.0` have below code (I used this gem to use v16)

File: `lib/google/ads/google_ads/v16/services/google_ads_service/client.rb`
Class: `Google:Ads:GoogleAds:V16:Services:GoogleAdsService`
```ruby
def initialize
....
                @google_ads_service_stub = ::Gapic::ServiceStub.new(
                  ::Google::Ads::GoogleAds::V16::Services::GoogleAdsService::Stub,
                  credentials: credentials,
                  endpoint: @config.endpoint,
                  endpoint_template: DEFAULT_ENDPOINT_TEMPLATE,
                  universe_domain: @config.universe_domain,
                  channel_args: @config.channel_args,
                  interceptors: @config.interceptors,
                  channel_pool_config: @config.channel_pool
                )
...
```
Above code `Gapic::ServiceStub` takes many parameters out of which two are
```
                  endpoint_template: DEFAULT_ENDPOINT_TEMPLATE,
                  universe_domain: @config.universe_domain,
```
The above 2 parameters are provided only in gem `gapic-common` version `0.21.1` and not `0.20.0`.
As mentioned on [rubygems.org](https://rubygems.org/gems/google-ads-googleads/versions/27.0.0?locale=en) below are the current dependencies for `google-ads-googleads` version `27.0.0`
```
[gapic-common](https://rubygems.org/gems/gapic-common) ~> 0.20
[google-protobuf](https://rubygems.org/gems/google-protobuf) >= 3.19.4, < 4.0
```

The below screenshot show the difference in the code of `gapic-common`
![image](https://github.com/googleads/google-ads-ruby/assets/48046456/bbdc20e8-657c-47ff-9f8e-7030f1315a41)

**Steps to Reproduce:**
Try initializing a client this way to observe the issue.
```ruby
        @client = Google::Ads::GoogleAds::GoogleAdsClient.new do |config|
          config.refresh_token = adwords_user.refresh_token
          config.client_id = ADWORDS_CONFIG['CLIENT_ID']
          config.client_secret = ADWORDS_CONFIG['CLIENT_SECRET']
          config.developer_token = ADWORDS_CONFIG['DEVELOPER_TOKEN']
          config.logger = Rails.logger
        end
```

**Expected behavior:**
The expected behavior is to make `google-ads-googleads` point to the right `gapic-common` version which is `0.21.1`

**Client library version and API version:**
Client library version: 27.0.0
Google Ads API version: v16

Gemfile.lock attached as (Gemfile.txt)
[Gemfile.txt](https://github.com/googleads/google-ads-ruby/files/14667711/Gemfile.txt)

**Comment by himanshu-patel-dev** [comment]
Please can I get someone from `googleads/google-ads-ruby` maintainers team to take a look. It's quite urgent. 
@mcloonan @danielfrg

**Comment by mcloonan** [comment]
Thanks for making the PR. Added one comment, and I'll merge once it's resolved.
