### ISSUE TITLE
Is this gem using RPC over HTTP2 ?

### ISSUE THREAD

**Issue by tdutreui-solocal** [googleads/google-ads-ruby#499]
Hi,
I am currently using the `gcr` gem to stub Google Ads API calls in my Rspec tests.
I saw here that it is possible to use gRPC over HTTP2 : https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

It would be more robust to me to use the common `vcr` gem to stub calls to your API, if these were done over HTTP.
Is there a way to make `google-ads-ruby` use gRPC over HTTP2 ?

Thank you
Thomas

**Comment by mcloonan** [comment]
I'm not sure whether the library uses gRPC over HTTP2 or not. You would get a better answer reaching out at the project that actually does the RPC layer of the library: https://github.com/googleapis/gapic-generator-ruby

**Comment by tdutreui-solocal** [comment]
Thank you ! let's go there
