### ISSUE TITLE
errors and partial failures details

### ISSUE THREAD

**Issue by apneadiving** [googleads/google-ads-ruby#50]
With adwords api, I would take N operations, do a dry run with partial_failure and validate_only.
Response would give me for each wrong operation: its index, the relevant error.
So I would know exactly which operations were invalid and why, so I could discard them and push the rest.

With google ads, sending 4 operations, 2 with known wrong arguments, I get:

```
<Google::Ads::GoogleAds::V1::Services::MutateCampaignBudgetsResponse: results: [], 
partial_failure_error: <Google::Rpc::Status: code: 3, message: "Multiple errors in ‘details’. First
 error: Too low., at operations[0].create.amount_micros", details: [<Google::Protobuf::Any:
 type_url: "type.googleapis.com/google.ads.googleads.v1.errors.GoogleAdsFailure", value: 
"\n<\n\x03\x88\x03\x02\x12\bToo low.\"+\x12\x0E\n\noperations\x12\x00\x12\b\n\x06create
\x12\x0F\n\ramount_micros\n;\n\x03\xB0\x03\x02\x12\nToo short.\x1A\x02*\x00\"$\x12\x10\n
\noperations\x12\x02\b\x01\x12\b\n\x06create\x12\x06\n\x04name">]>>
```

So:
- I do not know which operations are fine
- I do not know which are not 
- I dont have individual details for each errored operation (very handy to go back to data afterwards)
 
It would be ideal to have access to these information.

**Comment by mcloonan** [comment]
We're taking a look at this now.

**Comment by samphippen** [comment]
@apneadiving I'd encourage you to take a look at the pull request I've just filed. It makes it easier to work with `partial_failure_error` values by giving you a class which can decode them in to detailed proto error messages. Any feedback would be appreciated on that PR.

**Comment by apneadiving** [comment]
will give it a shot tomorrow, in the meantime, logging syntax caught my eye. So I did https://github.com/googleads/google-ads-ruby/pull/58/files

**Comment by apneadiving** [comment]
for some reason the classe isnt found but I got it to work copy/pasting the logic.

So we get a `Google::Ads::GoogleAds::V1::Errors::GoogleAdsFailure` which contains errors, that is fine.

I am trying to get relevant information from it and here its a little more tricky.

In my example I try and create a budget without name and 0 amount.

The error contains the following:
```
error.error_code #=> not that useful, or maybe there is a method to extract the not undefined one?
error.trigger #=> nil
error.details #=> nil
error.message #=> "Too low."
error.location.as_json #=> {"field_path_elements"=>[{"field_name"=>"operations", "index"=>{"value"=>2}}, {"field_name"=>"create", "index"=>nil}, {"field_name"=>"amount_micros", "index"=>nil}]}
```

So I have a few questions here:

- can I rely on the fact the operation error will always be the first one? Or should I select the `operations` field name?
- I created a budget with 0 amount and empty name, yet I can only see one error in location (amount_micros), does it make sense?

Thanks!

**Comment by mcloonan** [comment]
Some good feedback here, I'll reopen this so we can look into ways to make this even more usable. We are also planning a guide on [DevSite](https://developers.google.com/google-ads/api/) for partial failure in the near future.

Any given operation can only generate a single error. So if you fix the amount error, then you would get a different error for the budget name when you resubmit.

**Comment by apneadiving** [comment]
Do you intend to make the error_code more accessible? would be great to be able to extract it without having to loop all error_code possibilities. For instance `:RESOURCE_NOT_FOUND` is in `mutate_error`. 
Side question, do you guarantee there can be only one `UNSPECIFIED` field in `error_code`?

**Comment by apneadiving** [comment]
Seems I could hook `Google::Ads::GoogleAds::V1::Errors::ErrorCode.descriptor.lookup_oneof('error_code')` to get all possible error_code values. Would you like me to suggest a PR to help and extract info from errors?

**Comment by mcloonan** [comment]
Yes, there will only ever be one `error_code` in a given GoogleAdsError.

PRs always appreciated! Please just make sure to allow whatever you build to use an arbitrary version, not pinned to V1.

**Comment by apneadiving** [comment]
ok, will do, is there a standard way to fetch `Google::Ads::GoogleAds::VX::Errors::ErrorCode`?

**Comment by mcloonan** [comment]
We do something similar in LoggingInterceptor: https://github.com/googleads/google-ads-ruby/blob/master/lib/google/ads/google_ads/logging_interceptor.rb#L28

**Comment by apneadiving** [comment]
I am doing this to extract id out of a resource_name like `customers/1342647521/campaignBudgets/1826155367`

```
RESOURCE_NAME_REGEX = /([0-9]+)\/?$/`
def extract_id(resource_name)
  resource_name[RESOURCE_NAME_REGEX, 1]
end
```

Maybe I could add it somewhere in the gem, feels like a useful utility too

**Comment by mcloonan** [comment]
What is it that you need the ID for? Generally if you're only interacting with the Google Ads API, then the resource name is the unique identifier and extracting a specific ID generally isn't necessary.

**Comment by apneadiving** [comment]
maybe we could shit our way to proceed. We are moving the code from adwords api. So we are ids based (and recreate paths from this raw data).

I can understand its not useful for the gem though :)

**Comment by apneadiving** [comment]
shamelessly taking advantage of this thread, I have two questions:

-  is it a bug `campaign_shared_set` path only takes 2 arguments? I have to append manually the shared_set_id at the end for now: `path.campaign_shared_set(customer_id, campaign_id)  + "~#{adwords_id}"`
- what is the new version of the former `ManagedCustomerService` please?

**Comment by mcloonan** [comment]
Yes, the `campaign_shared_set` path should take 3 arguments. I'll make a PR for that shortly.

See [this example](https://github.com/googleads/google-ads-ruby/blob/master/examples/account_management/create_customer.rb) which demonstrates how to make a new account.

**Comment by apneadiving** [comment]
OK I see, so there is no operation there. What if I'd like to update it (change name basically) please?

**Comment by mcloonan** [comment]
In that case you'd use the mutate_customer method on the same service: https://github.com/googleads/google-ads-ruby/blob/master/lib/google/ads/google_ads/v1/services/customer_service_client.rb#L261

You may have to set the login_customer_id on the client for the customer you're updating before instantiating the service.

**Comment by mcloonan** [comment]
As for the main outstanding issue on this bug, do you consider it fixed with the PR you filed, or do you think there's more work to do?

**Comment by apneadiving** [comment]
I confirm its all good thank you :)
