### ISSUE TITLE
Authentication for Server to Server Apps

### ISSUE THREAD

**Issue by mpmenne** [googleads/google-ads-ruby#51]
Thanks for the examples of [OAuth Installed Application flow](https://github.com/googleads/google-ads-ruby/wiki/OAuth-Installed-Application-Flow) and [OAuth Web Application Flow](https://github.com/googleads/google-ads-ruby/wiki/OAuth-Web-Application-Flow).

Will the ruby client library also work using the [Server to Server Example](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) listed on the Google Identity Platform?

Do you have a short example or any tips on getting that started?

**Comment by mcloonan** [comment]
This is planned work for this lib, but unfortunately it's not implemented yet.

In the meanwhile most use cases are actually covered by using the installed application flow and storing the refresh token on your server.

**Comment by mpmenne** [comment]
Cool.  thanks!
