### ISSUE TITLE
compatible versions for gem "faraday"

### ISSUE THREAD

**Issue by ankitagarwal17** [googleads/google-ads-ruby#53]
Bundler could not find compatible versions for gem "faraday". This gem requires minimum v0.12 for faraday and I am using some other gems which require lesser version for faraday, due to which I am unable to install it in my rails application.

**Comment by samphippen** [comment]
Hi There!

The best advice I could give you is to determine which gems have incompatible faraday versions and attempt to update them to a newer version that depends on a more modern version of faraday. If you can't do that, the best course of action would be for you to send a patch to those gems to update their dependency.

From our perspective, we don't directly depend on faraday, specifically:
* this library depends on google-gax (`~> 1.4`)
* google-gax depends on googleauth
* googleauth resolves to faraday minimum at 0.12

As such,
