### ISSUE TITLE
GroupPlacementView proto has misaligned namespace

### ISSUE THREAD

**Issue by samphippen** [googleads/google-ads-ruby#79]
In [`resources/group_placement_view_pb.rb`](https://github.com/googleads/google-ads-ruby/blob/master/lib/google/ads/google_ads/v1/resources/group_placement_view_pb.rb#L19) the resource is generated in the `Google::Ads::GoogleAds::V1::Services` namespace. However, in [`services/group_placement_view_service_services_pb.rb`](https://github.com/googleads/google-ads-ruby/blob/master/lib/google/ads/google_ads/v1/services/group_placement_view_service_services_pb.rb) it's referred to under the resources namespace.

There is no place in the library where the group placement view proto is defined under the resources namespace.

**Comment by mcloonan** [comment]
Steps have been taken to try to ensure this doesn't happen again. A release step was added that loads all the proto files to make sure that they can be loaded, and we've fixed the source for these specific files so they should generate correctly next time.
